//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Source Executable: c:\windows\system32\windows.internal.devices.lights.backlightserver.dll
// Interface ID: 01ceb31c-6da7-44f8-b93b-a390db4f0d97
// Interface Version: 1.0
// Client Generated: 3/4/2026 7:38:45 PM
// NtApiDotNet Version: 1.1.33

namespace rpc_01ceb31c_6da7_44f8_b93b_a390db4f0d97_1_0
{
    
    #region Marshal Helpers
    internal class _Marshal_Helper : NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer
    {
    }
    internal class _Unmarshal_Helper : NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer
    {
        public _Unmarshal_Helper(NtApiDotNet.Win32.Rpc.RpcClientResponse r) : 
                base(r.NdrBuffer, r.Handles, r.DataRepresentation)
        {
        }
        public _Unmarshal_Helper(byte[] ba) : 
                base(ba)
        {
        }
    }
    #endregion
    #region Client Implementation
    public sealed class Client : NtApiDotNet.Win32.Rpc.RpcClientBase
    {
        public Client() : 
                base("01ceb31c-6da7-44f8-b93b-a390db4f0d97", 1, 0)
        {
        }
        private _Unmarshal_Helper SendReceive(int p, _Marshal_Helper m)
        {
            return new _Unmarshal_Helper(SendReceive(p, m.DataRepresentation, m.ToArray(), m.Handles));
        }
        public int BlcServerSetAutobrightnessEnabled(sbyte p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteSByte(p0);
            _Unmarshal_Helper u = SendReceive(0, m);
            return u.ReadInt32();
        }
        public int BlcServerSetEnergySaverDimmingEnabled(sbyte p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteSByte(p0);
            _Unmarshal_Helper u = SendReceive(1, m);
            return u.ReadInt32();
        }
        public int BlcServerSetBrightnessSliderPercentGlobal(int p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteInt32(p0);
            _Unmarshal_Helper u = SendReceive(2, m);
            return u.ReadInt32();
        }
    }
    #endregion
}

