//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Source Executable: c:\windows\system32\laps.dll
// Interface ID: 0fb2f016-fe45-4a08-a7f9-a467f5e5fa0b
// Interface Version: 1.0
// Client Generated: 3/4/2026 7:37:37 PM
// NtApiDotNet Version: 1.1.33

namespace rpc_0fb2f016_fe45_4a08_a7f9_a467f5e5fa0b_1_0
{
    
    #region Marshal Helpers
    internal class _Marshal_Helper : NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer
    {
        public void Write_0(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_1(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
    }
    internal class _Unmarshal_Helper : NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer
    {
        public _Unmarshal_Helper(NtApiDotNet.Win32.Rpc.RpcClientResponse r) : 
                base(r.NdrBuffer, r.Handles, r.DataRepresentation)
        {
        }
        public _Unmarshal_Helper(byte[] ba) : 
                base(ba)
        {
        }
        public byte[] Read_0()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_1()
        {
            return ReadConformantArray<byte>();
        }
    }
    #endregion
    #region Client Implementation
    public sealed class Client : NtApiDotNet.Win32.Rpc.RpcClientBase
    {
        public Client() : 
                base("0fb2f016-fe45-4a08-a7f9-a467f5e5fa0b", 1, 0)
        {
        }
        private _Unmarshal_Helper SendReceive(int p, _Marshal_Helper m)
        {
            return new _Unmarshal_Helper(SendReceive(p, m.DataRepresentation, m.ToArray(), m.Handles));
        }
        // async
        public int s_Ping(System.Guid p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            _Unmarshal_Helper u = SendReceive(0, m);
            return u.ReadInt32();
        }
        // async
        public int s_ProcessCurrentPolicy(System.Guid p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            _Unmarshal_Helper u = SendReceive(1, m);
            return u.ReadInt32();
        }
        // async
        public int s_PasswordResetSync(System.Guid p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            _Unmarshal_Helper u = SendReceive(2, m);
            return u.ReadInt32();
        }
        // async
        public int s_PasswordResetAsync(System.Guid p0, string p1, int p2, out System.Guid p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteReferent(p1, new System.Action<string>(m.WriteTerminatedString));
            m.WriteInt32(p2);
            _Unmarshal_Helper u = SendReceive(3, m);
            p3 = u.ReadGuid();
            return u.ReadInt32();
        }
        // async
        public int s_QueryPasswordResetAsyncStatus(System.Guid p0, System.Guid p1, out NtApiDotNet.Ndr.Marshal.NdrEnum16 p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteGuid(p1);
            _Unmarshal_Helper u = SendReceive(4, m);
            p2 = u.ReadEnum16();
            return u.ReadInt32();
        }
        // async
        public int s_QueryPasswordResetAsyncStatusByRequestId(System.Guid p0, string p1, out NtApiDotNet.Ndr.Marshal.NdrEnum16 p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            _Unmarshal_Helper u = SendReceive(5, m);
            p2 = u.ReadEnum16();
            return u.ReadInt32();
        }
        // async
        public int s_RecoverEncryptedMaterial(System.Guid p0, byte[] p1, int p2, out byte[] p3, out int p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.Write_0(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"), p2);
            m.WriteInt32(p2);
            _Unmarshal_Helper u = SendReceive(6, m);
            p3 = u.ReadReferent<byte[]>(new System.Func<byte[]>(u.Read_1), false);
            p4 = u.ReadInt32();
            return u.ReadInt32();
        }
        // async
        public int s_FlushPolicyCache(System.Guid p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            _Unmarshal_Helper u = SendReceive(7, m);
            return u.ReadInt32();
        }
        // async
        public int s_SetSuppressedOperations(System.Guid p0, int p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteInt32(p1);
            _Unmarshal_Helper u = SendReceive(8, m);
            return u.ReadInt32();
        }
    }
    #endregion
}

