//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Source Executable: c:\windows\system32\ngcctnrsvc.dll
// Interface ID: 2d24ff0b-1bab-404c-a0fd-42c85577bf68
// Interface Version: 1.0
// Client Generated: 3/4/2026 7:38:03 PM
// NtApiDotNet Version: 1.1.33

namespace rpc_2d24ff0b_1bab_404c_a0fd_42c85577bf68_1_0
{
    
    #region Marshal Helpers
    internal class _Marshal_Helper : NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer
    {
        public void Write_0(Struct_1 p0)
        {
            WriteStruct<Struct_1>(p0);
        }
        public void Write_1(Struct_2 p0)
        {
            WriteStruct<Struct_2>(p0);
        }
        public void Write_2(Struct_3 p0)
        {
            WriteStruct<Struct_3>(p0);
        }
        public void Write_3(Struct_4 p0)
        {
            WriteStruct<Struct_4>(p0);
        }
        public void Write_4(Struct_5 p0)
        {
            WriteStruct<Struct_5>(p0);
        }
        public void Write_5(Struct_6 p0)
        {
            WriteStruct<Struct_6>(p0);
        }
        public void Write_6(Struct_7 p0)
        {
            WriteStruct<Struct_7>(p0);
        }
        public void Write_7(Struct_8 p0)
        {
            WriteStruct<Struct_8>(p0);
        }
        public void Write_8(Struct_9 p0)
        {
            WriteStruct<Struct_9>(p0);
        }
        public void Write_9(Struct_10 p0)
        {
            WriteStruct<Struct_10>(p0);
        }
        public void Write_10(Struct_11 p0)
        {
            WriteStruct<Struct_11>(p0);
        }
        public void Write_11(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_12(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_13(Struct_4[] p0, long p1)
        {
            WriteConformantStructArray<Struct_4>(p0, p1);
        }
        public void Write_14(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_15(Struct_6[] p0, long p1)
        {
            WriteConformantStructArray<Struct_6>(p0, p1);
        }
        public void Write_16(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_17(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_18(Struct_9[] p0, long p1)
        {
            WriteConformantStructArray<Struct_9>(p0, p1);
        }
        public void Write_19(Struct_11[] p0, long p1)
        {
            WriteConformantStructArray<Struct_11>(p0, p1);
        }
        public void Write_20(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_21(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_22(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_23(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_24(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_25(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_26(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_27(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_28(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_29(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_30(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_31(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_32(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_33(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_34(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_35(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_36(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_37(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_38(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_39(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_40(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_41(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_42(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
    }
    internal class _Unmarshal_Helper : NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer
    {
        public _Unmarshal_Helper(NtApiDotNet.Win32.Rpc.RpcClientResponse r) : 
                base(r.NdrBuffer, r.Handles, r.DataRepresentation)
        {
        }
        public _Unmarshal_Helper(byte[] ba) : 
                base(ba)
        {
        }
        public Struct_1 Read_0()
        {
            return ReadStruct<Struct_1>();
        }
        public Struct_2 Read_1()
        {
            return ReadStruct<Struct_2>();
        }
        public Struct_3 Read_2()
        {
            return ReadStruct<Struct_3>();
        }
        public Struct_4 Read_3()
        {
            return ReadStruct<Struct_4>();
        }
        public Struct_5 Read_4()
        {
            return ReadStruct<Struct_5>();
        }
        public Struct_6 Read_5()
        {
            return ReadStruct<Struct_6>();
        }
        public Struct_7 Read_6()
        {
            return ReadStruct<Struct_7>();
        }
        public Struct_8 Read_7()
        {
            return ReadStruct<Struct_8>();
        }
        public Struct_9 Read_8()
        {
            return ReadStruct<Struct_9>();
        }
        public Struct_10 Read_9()
        {
            return ReadStruct<Struct_10>();
        }
        public Struct_11 Read_10()
        {
            return ReadStruct<Struct_11>();
        }
        public byte[] Read_11()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_12()
        {
            return ReadConformantArray<byte>();
        }
        public Struct_4[] Read_13()
        {
            return ReadConformantStructArray<Struct_4>();
        }
        public byte[] Read_14()
        {
            return ReadConformantArray<byte>();
        }
        public Struct_6[] Read_15()
        {
            return ReadConformantStructArray<Struct_6>();
        }
        public byte[] Read_16()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_17()
        {
            return ReadConformantArray<byte>();
        }
        public Struct_9[] Read_18()
        {
            return ReadConformantStructArray<Struct_9>();
        }
        public Struct_11[] Read_19()
        {
            return ReadConformantStructArray<Struct_11>();
        }
        public byte[] Read_20()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_21()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_22()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_23()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_24()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_25()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_26()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_27()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_28()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_29()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_30()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_31()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_32()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_33()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_34()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_35()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_36()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_37()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_38()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_39()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_40()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_41()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_42()
        {
            return ReadConformantArray<byte>();
        }
    }
    #endregion
    #region Complex Types
    public struct Struct_1 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteEnum16(Member0);
            m.WriteEmbeddedPointer<byte[], long>(Member8, new System.Action<byte[], long>(m.Write_11), Member10);
            m.WriteInt32(Member10);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadEnum16();
            Member8 = u.ReadEmbeddedPointer<byte[]>(new System.Func<byte[]>(u.Read_11), false);
            Member10 = u.ReadInt32();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public NtApiDotNet.Ndr.Marshal.NdrEnum16 Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<byte[]> Member8;
        public int Member10;
        public static Struct_1 CreateDefault()
        {
            return new Struct_1();
        }
        public Struct_1(NtApiDotNet.Ndr.Marshal.NdrEnum16 Member0, byte[] Member8, int Member10)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member10 = Member10;
        }
    }
    public struct Struct_2 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteEmbeddedPointer<string>(Member0, new System.Action<string>(m.WriteTerminatedString));
            m.WriteInt32(Member8);
            m.WriteEmbeddedPointer<byte[], long>(Member10, new System.Action<byte[], long>(m.Write_12), Member18);
            m.WriteInt32(Member18);
            m.Write_2(Member20);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member8 = u.ReadInt32();
            Member10 = u.ReadEmbeddedPointer<byte[]>(new System.Func<byte[]>(u.Read_12), false);
            Member18 = u.ReadInt32();
            Member20 = u.Read_2();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member0;
        public int Member8;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<byte[]> Member10;
        public int Member18;
        public Struct_3 Member20;
        public static Struct_2 CreateDefault()
        {
            return new Struct_2();
        }
        public Struct_2(string Member0, int Member8, byte[] Member10, int Member18, Struct_3 Member20)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member10 = Member10;
            this.Member18 = Member18;
            this.Member20 = Member20;
        }
    }
    public struct Struct_3 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteEmbeddedPointer<Struct_4[], long>(Member8, new System.Action<Struct_4[], long>(m.Write_13), Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<Struct_4[]>(new System.Func<Struct_4[]>(u.Read_13), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_4[]> Member8;
        public static Struct_3 CreateDefault()
        {
            return new Struct_3();
        }
        public Struct_3(int Member0, Struct_4[] Member8)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
        }
    }
    public struct Struct_4 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteEmbeddedPointer<string>(Member0, new System.Action<string>(m.WriteTerminatedString));
            m.WriteInt32(Member8);
            m.WriteEmbeddedPointer<byte[], long>(Member10, new System.Action<byte[], long>(m.Write_14), Member8);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member8 = u.ReadInt32();
            Member10 = u.ReadEmbeddedPointer<byte[]>(new System.Func<byte[]>(u.Read_14), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member0;
        public int Member8;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<byte[]> Member10;
        public static Struct_4 CreateDefault()
        {
            return new Struct_4();
        }
        public Struct_4(string Member0, int Member8, byte[] Member10)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member10 = Member10;
        }
    }
    public struct Struct_5 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteInt32(Member4);
            m.WriteEmbeddedPointer<Struct_6[], long>(Member8, new System.Action<Struct_6[], long>(m.Write_15), Member4);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member4 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<Struct_6[]>(new System.Func<Struct_6[]>(u.Read_15), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public int Member4;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_6[]> Member8;
        public static Struct_5 CreateDefault()
        {
            return new Struct_5();
        }
        public Struct_5(int Member0, int Member4, Struct_6[] Member8)
        {
            this.Member0 = Member0;
            this.Member4 = Member4;
            this.Member8 = Member8;
        }
    }
    public struct Struct_6 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteInt32(Member4);
            m.WriteEmbeddedPointer<byte[], long>(Member8, new System.Action<byte[], long>(m.Write_16), Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member4 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<byte[]>(new System.Func<byte[]>(u.Read_16), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public int Member4;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<byte[]> Member8;
        public static Struct_6 CreateDefault()
        {
            return new Struct_6();
        }
        public Struct_6(int Member0, int Member4, byte[] Member8)
        {
            this.Member0 = Member0;
            this.Member4 = Member4;
            this.Member8 = Member8;
        }
    }
    public struct Struct_7 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteEmbeddedPointer<string>(Member0, new System.Action<string>(m.WriteTerminatedString));
            m.WriteInt32(Member8);
            m.WriteInt32(MemberC);
            m.WriteInt32(Member10);
            m.WriteInt32(Member14);
            m.WriteEmbeddedPointer<byte[], long>(Member18, new System.Action<byte[], long>(m.Write_17), Member14);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member8 = u.ReadInt32();
            MemberC = u.ReadInt32();
            Member10 = u.ReadInt32();
            Member14 = u.ReadInt32();
            Member18 = u.ReadEmbeddedPointer<byte[]>(new System.Func<byte[]>(u.Read_17), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member0;
        public int Member8;
        public int MemberC;
        public int Member10;
        public int Member14;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<byte[]> Member18;
        public static Struct_7 CreateDefault()
        {
            return new Struct_7();
        }
        public Struct_7(string Member0, int Member8, int MemberC, int Member10, int Member14, byte[] Member18)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.MemberC = MemberC;
            this.Member10 = Member10;
            this.Member14 = Member14;
            this.Member18 = Member18;
        }
    }
    public struct Struct_8 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteEmbeddedPointer<Struct_9[], long>(Member8, new System.Action<Struct_9[], long>(m.Write_18), Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<Struct_9[]>(new System.Func<Struct_9[]>(u.Read_18), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_9[]> Member8;
        public static Struct_8 CreateDefault()
        {
            return new Struct_8();
        }
        public Struct_8(int Member0, Struct_9[] Member8)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
        }
    }
    public struct Struct_9 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteGuid(Member0);
            m.WriteEmbeddedPointer<string>(Member10, new System.Action<string>(m.WriteTerminatedString));
            m.WriteInt32(Member18);
            m.WriteInt32(Member1C);
            m.WriteEnum16(Member20);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadGuid();
            Member10 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member18 = u.ReadInt32();
            Member1C = u.ReadInt32();
            Member20 = u.ReadEnum16();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public System.Guid Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member10;
        public int Member18;
        public int Member1C;
        public NtApiDotNet.Ndr.Marshal.NdrEnum16 Member20;
        public static Struct_9 CreateDefault()
        {
            return new Struct_9();
        }
        public Struct_9(System.Guid Member0, string Member10, int Member18, int Member1C, NtApiDotNet.Ndr.Marshal.NdrEnum16 Member20)
        {
            this.Member0 = Member0;
            this.Member10 = Member10;
            this.Member18 = Member18;
            this.Member1C = Member1C;
            this.Member20 = Member20;
        }
    }
    public struct Struct_10 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteEmbeddedPointer<Struct_11[], long>(Member8, new System.Action<Struct_11[], long>(m.Write_19), Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<Struct_11[]>(new System.Func<Struct_11[]>(u.Read_19), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_11[]> Member8;
        public static Struct_10 CreateDefault()
        {
            return new Struct_10();
        }
        public Struct_10(int Member0, Struct_11[] Member8)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
        }
    }
    public struct Struct_11 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteEmbeddedPointer<string>(Member0, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member8, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member10, new System.Action<string>(m.WriteTerminatedString));
            m.WriteInt32(Member18);
            m.WriteInt32(Member1C);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member8 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member10 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member18 = u.ReadInt32();
            Member1C = u.ReadInt32();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member8;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member10;
        public int Member18;
        public int Member1C;
        public static Struct_11 CreateDefault()
        {
            return new Struct_11();
        }
        public Struct_11(string Member0, string Member8, string Member10, int Member18, int Member1C)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member10 = Member10;
            this.Member18 = Member18;
            this.Member1C = Member1C;
        }
    }
    #endregion
    #region Client Implementation
    public sealed class Client : NtApiDotNet.Win32.Rpc.RpcClientBase
    {
        public Client() : 
                base("2d24ff0b-1bab-404c-a0fd-42c85577bf68", 1, 0)
        {
        }
        private _Unmarshal_Helper SendReceive(int p, _Marshal_Helper m)
        {
            return new _Unmarshal_Helper(SendReceive(p, m.DataRepresentation, m.ToArray(), m.Handles));
        }
        public int s_NgcHandlerRpcAuthenticateGesture(System.Guid p0, Struct_1 p1, out long p2, ref System.Nullable<long> p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.Write_0(p1);
            m.WriteReferent(p3, new System.Action<long>(m.WriteInt64));
            _Unmarshal_Helper u = SendReceive(0, m);
            p2 = u.ReadInt64();
            p3 = u.ReadReferentValue<long>(new System.Func<long>(u.ReadInt64), false);
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcDeauthenticate(System.Guid p0, NtApiDotNet.Ndr.Marshal.NdrEnum16 p1, long p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteEnum16(p1);
            m.WriteInt64(p2);
            _Unmarshal_Helper u = SendReceive(1, m);
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcChangePin(System.Guid p0, byte[] p1, int p2, byte[] p3, int p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.Write_20(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"), p2);
            m.WriteInt32(p2);
            m.Write_21(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p3, "p3"), p4);
            m.WriteInt32(p4);
            _Unmarshal_Helper u = SendReceive(2, m);
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcRecoverPin(System.Guid p0, byte[] p1, int p2, byte[] p3, int p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.Write_20(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"), p2);
            m.WriteInt32(p2);
            m.Write_21(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p3, "p3"), p4);
            m.WriteInt32(p4);
            _Unmarshal_Helper u = SendReceive(3, m);
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcAddBioProtector(System.Guid p0, long p1, long p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteInt64(p1);
            m.WriteInt64(p2);
            _Unmarshal_Helper u = SendReceive(4, m);
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcRemoveBioProtector(System.Guid p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            _Unmarshal_Helper u = SendReceive(5, m);
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcAddPrebootProtector(System.Guid p0, long p1, long p2, byte[] p3, int p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteInt64(p1);
            m.WriteInt64(p2);
            m.Write_21(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p3, "p3"), p4);
            m.WriteInt32(p4);
            _Unmarshal_Helper u = SendReceive(6, m);
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcRemovePrebootProtector(System.Guid p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            _Unmarshal_Helper u = SendReceive(7, m);
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcAddCompanionDeviceProtector(System.Guid p0, long p1, long p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteInt64(p1);
            m.WriteInt64(p2);
            _Unmarshal_Helper u = SendReceive(8, m);
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcRemoveCompanionDeviceProtector(System.Guid p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            _Unmarshal_Helper u = SendReceive(9, m);
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcSignHash(System.Guid p0, long p1, string p2, string p3, string p4, System.Nullable<Struct_2> p5, byte[] p6, int p7, int p8, byte[] p9, int p10, out byte[] p11, out int p12, out byte[] p13, out int p14)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteInt64(p1);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p3, "p3"));
            m.WriteReferent(p4, new System.Action<string>(m.WriteTerminatedString));
            m.WriteReferent(p5, new System.Action<Struct_2>(m.Write_1));
            m.Write_22(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p6, "p6"), p7);
            m.WriteInt32(p7);
            m.WriteInt32(p8);
            m.WriteReferent(p9, new System.Action<byte[], long>(m.Write_23), p10);
            m.WriteInt32(p10);
            _Unmarshal_Helper u = SendReceive(10, m);
            p11 = u.ReadReferent<byte[]>(new System.Func<byte[]>(u.Read_24), false);
            p12 = u.ReadInt32();
            p13 = u.ReadReferent<byte[]>(new System.Func<byte[]>(u.Read_25), false);
            p14 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcRsaDecryptWithPkcs1(System.Guid p0, long p1, string p2, string p3, string p4, byte[] p5, int p6, out byte[] p7, out int p8)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteInt64(p1);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p3, "p3"));
            m.WriteReferent(p4, new System.Action<string>(m.WriteTerminatedString));
            m.Write_26(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p5, "p5"), p6);
            m.WriteInt32(p6);
            _Unmarshal_Helper u = SendReceive(11, m);
            p7 = u.ReadReferent<byte[]>(new System.Func<byte[]>(u.Read_27), false);
            p8 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcSecretAgreement(System.Guid p0, long p1, string p2, string p3, string p4, byte[] p5, int p6, int p7, out long p8)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteInt64(p1);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p3, "p3"));
            m.WriteReferent(p4, new System.Action<string>(m.WriteTerminatedString));
            m.Write_26(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p5, "p5"), p6);
            m.WriteInt32(p6);
            m.WriteInt32(p7);
            _Unmarshal_Helper u = SendReceive(12, m);
            p8 = u.ReadInt64();
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcDeriveKey(System.Guid p0, long p1, string p2, System.Nullable<Struct_5> p3, ref byte[] p4, int p5, out int p6, int p7)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteInt64(p1);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"));
            m.WriteReferent(p3, new System.Action<Struct_5>(m.Write_4));
            m.WriteReferent(p4, new System.Action<byte[], long>(m.Write_28), p5);
            m.WriteInt32(p5);
            m.WriteInt32(p7);
            _Unmarshal_Helper u = SendReceive(13, m);
            p4 = u.ReadReferent<byte[]>(new System.Func<byte[]>(u.Read_28), false);
            p6 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcFreeSecret(System.Guid p0, long p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteInt64(p1);
            _Unmarshal_Helper u = SendReceive(14, m);
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcAuthenticatedReqResp(System.Guid p0, long p1, string p2, string p3, string p4, byte[] p5, int p6, out byte[] p7, out int p8)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteInt64(p1);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p3, "p3"));
            m.WriteReferent(p4, new System.Action<string>(m.WriteTerminatedString));
            m.Write_26(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p5, "p5"), p6);
            m.WriteInt32(p6);
            _Unmarshal_Helper u = SendReceive(15, m);
            p7 = u.ReadReferent<byte[]>(new System.Func<byte[]>(u.Read_27), false);
            p8 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcCreateKey(
                    System.Guid p0, 
                    long p1, 
                    int p2, 
                    string p3, 
                    int p4, 
                    int p5, 
                    int p6, 
                    string p7, 
                    string p8, 
                    string p9, 
                    byte[] p10, 
                    int p11, 
                    Struct_7 p12, 
                    int p13, 
                    int p14, 
                    byte[] p15, 
                    int p16, 
                    out byte[] p17, 
                    out int p18)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteInt64(p1);
            m.WriteInt32(p2);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p3, "p3"));
            m.WriteInt32(p4);
            m.WriteInt32(p5);
            m.WriteInt32(p6);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p7, "p7"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p8, "p8"));
            m.WriteReferent(p9, new System.Action<string>(m.WriteTerminatedString));
            m.WriteReferent(p10, new System.Action<byte[], long>(m.Write_29), p11);
            m.WriteInt32(p11);
            m.Write_6(p12);
            m.WriteInt32(p13);
            m.WriteInt32(p14);
            m.WriteReferent(p15, new System.Action<byte[], long>(m.Write_30), p16);
            m.WriteInt32(p16);
            _Unmarshal_Helper u = SendReceive(16, m);
            p17 = u.ReadReferent<byte[]>(new System.Func<byte[]>(u.Read_31), false);
            p18 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcRsaImportKey(
                    System.Guid p0, 
                    long p1, 
                    int p2, 
                    int p3, 
                    int p4, 
                    string p5, 
                    string p6, 
                    string p7, 
                    int p8, 
                    byte[] p9, 
                    int p10, 
                    byte[] p11, 
                    int p12, 
                    byte[] p13, 
                    int p14, 
                    byte[] p15, 
                    int p16, 
                    byte[] p17, 
                    int p18, 
                    byte[] p19, 
                    int p20, 
                    byte[] p21, 
                    int p22, 
                    byte[] p23, 
                    int p24)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteInt64(p1);
            m.WriteInt32(p2);
            m.WriteInt32(p3);
            m.WriteInt32(p4);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p5, "p5"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p6, "p6"));
            m.WriteReferent(p7, new System.Action<string>(m.WriteTerminatedString));
            m.WriteInt32(p8);
            m.Write_23(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p9, "p9"), p10);
            m.WriteInt32(p10);
            m.Write_32(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p11, "p11"), p12);
            m.WriteInt32(p12);
            m.Write_33(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p13, "p13"), p14);
            m.WriteInt32(p14);
            m.Write_30(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p15, "p15"), p16);
            m.WriteInt32(p16);
            m.Write_34(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p17, "p17"), p18);
            m.WriteInt32(p18);
            m.Write_35(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p19, "p19"), p20);
            m.WriteInt32(p20);
            m.Write_36(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p21, "p21"), p22);
            m.WriteInt32(p22);
            m.Write_37(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p23, "p23"), p24);
            m.WriteInt32(p24);
            _Unmarshal_Helper u = SendReceive(17, m);
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcExportKey(System.Guid p0, long p1, string p2, string p3, string p4, string p5, out byte[] p6, out int p7)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteInt64(p1);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p3, "p3"));
            m.WriteReferent(p4, new System.Action<string>(m.WriteTerminatedString));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p5, "p5"));
            _Unmarshal_Helper u = SendReceive(18, m);
            p6 = u.ReadReferent<byte[]>(new System.Func<byte[]>(u.Read_38), false);
            p7 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcRsaExportPublicKey(System.Guid p0, string p1, string p2, string p3, out byte[] p4, out int p5, out byte[] p6, out int p7)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"));
            m.WriteReferent(p3, new System.Action<string>(m.WriteTerminatedString));
            _Unmarshal_Helper u = SendReceive(19, m);
            p4 = u.ReadReferent<byte[]>(new System.Func<byte[]>(u.Read_39), false);
            p5 = u.ReadInt32();
            p6 = u.ReadReferent<byte[]>(new System.Func<byte[]>(u.Read_38), false);
            p7 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcOpenKey(System.Guid p0, string p1, string p2, string p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"));
            m.WriteReferent(p3, new System.Action<string>(m.WriteTerminatedString));
            _Unmarshal_Helper u = SendReceive(20, m);
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcCloseKey(System.Guid p0, string p1, string p2, string p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"));
            m.WriteReferent(p3, new System.Action<string>(m.WriteTerminatedString));
            _Unmarshal_Helper u = SendReceive(21, m);
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcRsaDeleteKey(System.Guid p0, string p1, string p2, string p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"));
            m.WriteReferent(p3, new System.Action<string>(m.WriteTerminatedString));
            _Unmarshal_Helper u = SendReceive(22, m);
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcEnumContainers(out System.Nullable<Struct_8> p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(23, m);
            p0 = u.ReadReferentValue<Struct_8>(new System.Func<Struct_8>(u.Read_7), false);
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcEnumKeys(System.Guid p0, out System.Nullable<Struct_10> p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            _Unmarshal_Helper u = SendReceive(24, m);
            p1 = u.ReadReferentValue<Struct_10>(new System.Func<Struct_10>(u.Read_9), false);
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcSetKeyMetadata(System.Guid p0, long p1, string p2, string p3, string p4, NtApiDotNet.Ndr.Marshal.NdrEnum16 p5, byte[] p6, int p7)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteInt64(p1);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p3, "p3"));
            m.WriteReferent(p4, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEnum16(p5);
            m.Write_22(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p6, "p6"), p7);
            m.WriteInt32(p7);
            _Unmarshal_Helper u = SendReceive(25, m);
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcGetKeyMetadata(System.Guid p0, string p1, string p2, string p3, NtApiDotNet.Ndr.Marshal.NdrEnum16 p4, out byte[] p5, out int p6)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"));
            m.WriteReferent(p3, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEnum16(p4);
            _Unmarshal_Helper u = SendReceive(26, m);
            p5 = u.ReadReferent<byte[]>(new System.Func<byte[]>(u.Read_40), false);
            p6 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcSetContainerMetadata(System.Guid p0, NtApiDotNet.Ndr.Marshal.NdrEnum16 p1, byte[] p2, int p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteEnum16(p1);
            m.Write_41(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"), p3);
            m.WriteInt32(p3);
            _Unmarshal_Helper u = SendReceive(27, m);
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcGetContainerMetadata(System.Guid p0, NtApiDotNet.Ndr.Marshal.NdrEnum16 p1, out byte[] p2, out int p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteEnum16(p1);
            _Unmarshal_Helper u = SendReceive(28, m);
            p2 = u.ReadReferent<byte[]>(new System.Func<byte[]>(u.Read_42), false);
            p3 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcGetTrustletSignedPublicKey(System.Guid p0, string p1, string p2, string p3, string p4, byte[] p5, int p6, out byte[] p7, out int p8)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"));
            m.WriteReferent(p3, new System.Action<string>(m.WriteTerminatedString));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p4, "p4"));
            m.Write_26(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p5, "p5"), p6);
            m.WriteInt32(p6);
            _Unmarshal_Helper u = SendReceive(29, m);
            p7 = u.ReadReferent<byte[]>(new System.Func<byte[]>(u.Read_27), false);
            p8 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcGetSessionChallenge(System.Guid p0, string p1, string p2, string p3, out byte[] p4, out int p5)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"));
            m.WriteReferent(p3, new System.Action<string>(m.WriteTerminatedString));
            _Unmarshal_Helper u = SendReceive(30, m);
            p4 = u.ReadReferent<byte[]>(new System.Func<byte[]>(u.Read_39), false);
            p5 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcSetClientAttestation(System.Guid p0, string p1, string p2, string p3, byte[] p4, int p5)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"));
            m.WriteReferent(p3, new System.Action<string>(m.WriteTerminatedString));
            m.Write_28(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p4, "p4"), p5);
            m.WriteInt32(p5);
            _Unmarshal_Helper u = SendReceive(31, m);
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcGetKeyAikCertificate(System.Guid p0, string p1, string p2, string p3, out byte[] p4, out int p5)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"));
            m.WriteReferent(p3, new System.Action<string>(m.WriteTerminatedString));
            _Unmarshal_Helper u = SendReceive(32, m);
            p4 = u.ReadReferent<byte[]>(new System.Func<byte[]>(u.Read_39), false);
            p5 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcCreateClaim(System.Guid p0, long p1, string p2, string p3, string p4, byte[] p5, int p6, out byte[] p7, out int p8)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteInt64(p1);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p3, "p3"));
            m.WriteReferent(p4, new System.Action<string>(m.WriteTerminatedString));
            m.WriteReferent(p5, new System.Action<byte[], long>(m.Write_26), p6);
            m.WriteInt32(p6);
            _Unmarshal_Helper u = SendReceive(33, m);
            p7 = u.ReadReferent<byte[]>(new System.Func<byte[]>(u.Read_27), false);
            p8 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcCreateMonotonicCounter(System.Guid p0, string p1, string p2, string p3, byte[] p4, int p5)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"));
            m.WriteReferent(p3, new System.Action<string>(m.WriteTerminatedString));
            m.WriteReferent(p4, new System.Action<byte[], long>(m.Write_28), p5);
            m.WriteInt32(p5);
            _Unmarshal_Helper u = SendReceive(34, m);
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcQueryMonotonicCounter(System.Guid p0, string p1, string p2, string p3, out byte[] p4, out int p5)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"));
            m.WriteReferent(p3, new System.Action<string>(m.WriteTerminatedString));
            _Unmarshal_Helper u = SendReceive(35, m);
            p4 = u.ReadReferent<byte[]>(new System.Func<byte[]>(u.Read_39), false);
            p5 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int s_NgcHandlerRpcIncrementMonotonicCounter(System.Guid p0, string p1, string p2, string p3, byte[] p4, int p5)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"));
            m.WriteReferent(p3, new System.Action<string>(m.WriteTerminatedString));
            m.WriteReferent(p4, new System.Action<byte[], long>(m.Write_28), p5);
            m.WriteInt32(p5);
            _Unmarshal_Helper u = SendReceive(36, m);
            return u.ReadInt32();
        }
    }
    #endregion
}

