//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Source Executable: c:\windows\system32\mispace.dll
// Interface ID: 58b19028-b9a0-4c25-887f-aca58b584d1b
// Interface Version: 1.0
// Client Generated: 3/4/2026 7:37:45 PM
// NtApiDotNet Version: 1.1.33

namespace rpc_58b19028_b9a0_4c25_887f_aca58b584d1b_1_0
{
    
    #region Marshal Helpers
    internal class _Marshal_Helper : NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer
    {
        public void Write_0(NtApiDotNet.NtToken p0)
        {
            WriteSystemHandle<NtApiDotNet.NtToken>(p0);
        }
        public void Write_1(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_2(byte[] p0, long p1, long p2)
        {
            WriteConformantVaryingArray<byte>(p0, p1, p2);
        }
    }
    internal class _Unmarshal_Helper : NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer
    {
        public _Unmarshal_Helper(NtApiDotNet.Win32.Rpc.RpcClientResponse r) : 
                base(r.NdrBuffer, r.Handles, r.DataRepresentation)
        {
        }
        public _Unmarshal_Helper(byte[] ba) : 
                base(ba)
        {
        }
        public NtApiDotNet.NtToken Read_0()
        {
            return ReadSystemHandle<NtApiDotNet.NtToken>();
        }
        public byte[] Read_1()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_2()
        {
            return ReadConformantVaryingArray<byte>();
        }
    }
    #endregion
    #region Client Implementation
    public sealed class Client : NtApiDotNet.Win32.Rpc.RpcClientBase
    {
        public Client() : 
                base("58b19028-b9a0-4c25-887f-aca58b584d1b", 1, 0)
        {
        }
        private _Unmarshal_Helper SendReceive(int p, _Marshal_Helper m)
        {
            return new _Unmarshal_Helper(SendReceive(p, m.DataRepresentation, m.ToArray(), m.Handles));
        }
        public int ClusterSpaceControl(NtApiDotNet.NtToken p0, byte[] p1, int p2, out byte[] p3, int p4, out int p5)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.Write_0(p0);
            m.Write_1(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"), p2);
            m.WriteInt32(p2);
            m.WriteInt32(p4);
            _Unmarshal_Helper u = SendReceive(0, m);
            p3 = u.Read_2();
            p5 = u.ReadInt32();
            return u.ReadInt32();
        }
    }
    #endregion
}

