//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Source Executable: c:\windows\system32\midisrv.exe
// Interface ID: 64839251-9daf-4e79-aa4e-9771c86ffbc1
// Interface Version: 1.0
// Client Generated: 3/4/2026 7:37:44 PM
// NtApiDotNet Version: 1.1.33

namespace rpc_64839251_9daf_4e79_aa4e_9771c86ffbc1_1_0
{
    
    #region Marshal Helpers
    internal class _Marshal_Helper : NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer
    {
        public void Write_0(Struct_0 p0)
        {
            WriteStruct<Struct_0>(p0);
        }
        public void Write_1(Struct_2 p0)
        {
            WriteStruct<Struct_2>(p0);
        }
        public void Write_2(NtApiDotNet.NtEvent p0)
        {
            WriteSystemHandle<NtApiDotNet.NtEvent>(p0);
        }
        public void Write_3(NtApiDotNet.NtSection p0)
        {
            WriteSystemHandle<NtApiDotNet.NtSection>(p0);
        }
    }
    internal class _Unmarshal_Helper : NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer
    {
        public _Unmarshal_Helper(NtApiDotNet.Win32.Rpc.RpcClientResponse r) : 
                base(r.NdrBuffer, r.Handles, r.DataRepresentation)
        {
        }
        public _Unmarshal_Helper(byte[] ba) : 
                base(ba)
        {
        }
        public Struct_0 Read_0()
        {
            return ReadStruct<Struct_0>();
        }
        public Struct_2 Read_1()
        {
            return ReadStruct<Struct_2>();
        }
        public NtApiDotNet.NtEvent Read_2()
        {
            return ReadSystemHandle<NtApiDotNet.NtEvent>();
        }
        public NtApiDotNet.NtSection Read_3()
        {
            return ReadSystemHandle<NtApiDotNet.NtSection>();
        }
    }
    #endregion
    #region Complex Types
    public struct Struct_0 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteEnum16(Member0);
            m.WriteEnum16(Member4);
            m.WriteEnum16(Member8);
            m.WriteInt32(MemberC);
            m.WriteGuid(Member10);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadEnum16();
            Member4 = u.ReadEnum16();
            Member8 = u.ReadEnum16();
            MemberC = u.ReadInt32();
            Member10 = u.ReadGuid();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public NtApiDotNet.Ndr.Marshal.NdrEnum16 Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEnum16 Member4;
        public NtApiDotNet.Ndr.Marshal.NdrEnum16 Member8;
        public int MemberC;
        public System.Guid Member10;
        public static Struct_0 CreateDefault()
        {
            return new Struct_0();
        }
        public Struct_0(NtApiDotNet.Ndr.Marshal.NdrEnum16 Member0, NtApiDotNet.Ndr.Marshal.NdrEnum16 Member4, NtApiDotNet.Ndr.Marshal.NdrEnum16 Member8, int MemberC, System.Guid Member10)
        {
            this.Member0 = Member0;
            this.Member4 = Member4;
            this.Member8 = Member8;
            this.MemberC = MemberC;
            this.Member10 = Member10;
        }
    }
    public struct Struct_2 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.Write_2(Member0);
            m.Write_2(Member8);
            m.Write_2(Member10);
            m.Write_2(Member18);
            m.Write_3(Member20);
            m.Write_3(Member28);
            m.Write_3(Member30);
            m.Write_3(Member38);
            m.WriteInt32(Member40);
            m.WriteInt32(Member44);
            m.WriteInt64(Member48);
            m.WriteEnum16(Member50);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.Read_2();
            Member8 = u.Read_2();
            Member10 = u.Read_2();
            Member18 = u.Read_2();
            Member20 = u.Read_3();
            Member28 = u.Read_3();
            Member30 = u.Read_3();
            Member38 = u.Read_3();
            Member40 = u.ReadInt32();
            Member44 = u.ReadInt32();
            Member48 = u.ReadInt64();
            Member50 = u.ReadEnum16();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public NtApiDotNet.NtEvent Member0;
        public NtApiDotNet.NtEvent Member8;
        public NtApiDotNet.NtEvent Member10;
        public NtApiDotNet.NtEvent Member18;
        public NtApiDotNet.NtSection Member20;
        public NtApiDotNet.NtSection Member28;
        public NtApiDotNet.NtSection Member30;
        public NtApiDotNet.NtSection Member38;
        public int Member40;
        public int Member44;
        public long Member48;
        public NtApiDotNet.Ndr.Marshal.NdrEnum16 Member50;
        public static Struct_2 CreateDefault()
        {
            return new Struct_2();
        }
        public Struct_2(NtApiDotNet.NtEvent Member0, NtApiDotNet.NtEvent Member8, NtApiDotNet.NtEvent Member10, NtApiDotNet.NtEvent Member18, NtApiDotNet.NtSection Member20, NtApiDotNet.NtSection Member28, NtApiDotNet.NtSection Member30, NtApiDotNet.NtSection Member38, int Member40, int Member44, long Member48, NtApiDotNet.Ndr.Marshal.NdrEnum16 Member50)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member10 = Member10;
            this.Member18 = Member18;
            this.Member20 = Member20;
            this.Member28 = Member28;
            this.Member30 = Member30;
            this.Member38 = Member38;
            this.Member40 = Member40;
            this.Member44 = Member44;
            this.Member48 = Member48;
            this.Member50 = Member50;
        }
    }
    #endregion
    #region Client Implementation
    public sealed class Client : NtApiDotNet.Win32.Rpc.RpcClientBase
    {
        public Client() : 
                base("64839251-9daf-4e79-aa4e-9771c86ffbc1", 1, 0)
        {
        }
        private _Unmarshal_Helper SendReceive(int p, _Marshal_Helper m)
        {
            return new _Unmarshal_Helper(SendReceive(p, m.DataRepresentation, m.ToArray(), m.Handles));
        }
        public int MidiSrvCreateClient(string p0, Struct_0 p1, System.Guid p2, out System.Nullable<Struct_2> p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.Write_0(p1);
            m.WriteGuid(p2);
            _Unmarshal_Helper u = SendReceive(0, m);
            p3 = u.ReadReferentValue<Struct_2>(new System.Func<Struct_2>(u.Read_1), false);
            return u.ReadInt32();
        }
        public int MidiSrvDestroyClient(long p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteInt64(p0);
            _Unmarshal_Helper u = SendReceive(1, m);
            return u.ReadInt32();
        }
        public int MidiSrvUpdateConfiguration(string p0, out string p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            _Unmarshal_Helper u = SendReceive(2, m);
            p1 = u.ReadReferent<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            return u.ReadInt32();
        }
        public int MidiSrvRegisterSession(System.Guid p0, string p1, ref NtApiDotNet.Ndr.Marshal.NdrContextHandle p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            m.WriteContextHandle(p2);
            _Unmarshal_Helper u = SendReceive(3, m);
            p2 = u.ReadContextHandle();
            return u.ReadInt32();
        }
        public int MidiSrvUpdateSessionName(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, System.Guid p1, string p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteGuid(p1);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"));
            _Unmarshal_Helper u = SendReceive(4, m);
            return u.ReadInt32();
        }
        public int MidiSrvDeregisterSession(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, System.Guid p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteGuid(p1);
            _Unmarshal_Helper u = SendReceive(5, m);
            return u.ReadInt32();
        }
        public int MidiSrvGetSessionList(out string p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(6, m);
            p0 = u.ReadReferent<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            return u.ReadInt32();
        }
        public int MidiSrvGetTransportList(out string p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(7, m);
            p0 = u.ReadReferent<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            return u.ReadInt32();
        }
        public int MidiSrvGetTransformList(out string p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(8, m);
            p0 = u.ReadReferent<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            return u.ReadInt32();
        }
        public int MidiSrvVerifyConnectivity()
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(9, m);
            return u.ReadInt32();
        }
    }
    #endregion
}

