//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Source Executable: c:\windows\system32\psmsrv.dll
// Interface ID: 8782d3b9-ebbd-4644-a3d8-e8725381919b
// Interface Version: 1.0
// Client Generated: 3/4/2026 7:38:14 PM
// NtApiDotNet Version: 1.1.33

namespace rpc_8782d3b9_ebbd_4644_a3d8_e8725381919b_1_0
{
    
    #region Marshal Helpers
    internal class _Marshal_Helper : NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer
    {
        public void Write_0(NtApiDotNet.NtSemaphore p0)
        {
            WriteSystemHandle<NtApiDotNet.NtSemaphore>(p0);
        }
        public void Write_1(NtApiDotNet.NtEvent p0)
        {
            WriteSystemHandle<NtApiDotNet.NtEvent>(p0);
        }
    }
    internal class _Unmarshal_Helper : NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer
    {
        public _Unmarshal_Helper(NtApiDotNet.Win32.Rpc.RpcClientResponse r) : 
                base(r.NdrBuffer, r.Handles, r.DataRepresentation)
        {
        }
        public _Unmarshal_Helper(byte[] ba) : 
                base(ba)
        {
        }
        public NtApiDotNet.NtSemaphore Read_0()
        {
            return ReadSystemHandle<NtApiDotNet.NtSemaphore>();
        }
        public NtApiDotNet.NtEvent Read_1()
        {
            return ReadSystemHandle<NtApiDotNet.NtEvent>();
        }
    }
    #endregion
    #region Client Implementation
    public sealed class Client : NtApiDotNet.Win32.Rpc.RpcClientBase
    {
        public Client() : 
                base("8782d3b9-ebbd-4644-a3d8-e8725381919b", 1, 0)
        {
        }
        private _Unmarshal_Helper SendReceive(int p, _Marshal_Helper m)
        {
            return new _Unmarshal_Helper(SendReceive(p, m.DataRepresentation, m.ToArray(), m.Handles));
        }
        public int PsmSrvRegisterQuiesceResumeApp(out NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, out sbyte p1, out NtApiDotNet.NtSemaphore p2, out NtApiDotNet.NtEvent p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(0, m);
            p0 = u.ReadContextHandle();
            p1 = u.ReadSByte();
            p2 = u.Read_0();
            p3 = u.Read_1();
            return u.ReadInt32();
        }
        public int PsmSrvQuiesceCallbacksComplete(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(1, m);
            return u.ReadInt32();
        }
        public int PsmSrvCloseActivationChannel(ref NtApiDotNet.Ndr.Marshal.NdrContextHandle p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(2, m);
            p0 = u.ReadContextHandle();
            return u.ReadInt32();
        }
    }
    #endregion
}

