//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Source Executable: c:\windows\system32\audiosrv.dll
// Interface ID: 923f85b3-bbee-4edf-8059-f569fa64a027
// Interface Version: 1.6
// Client Generated: 3/4/2026 7:36:50 PM
// NtApiDotNet Version: 1.1.33

namespace rpc_923f85b3_bbee_4edf_8059_f569fa64a027_1_6
{
    
    #region Marshal Helpers
    internal class _Marshal_Helper : NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer
    {
        public void Write_0(Struct_1 p0)
        {
            WriteStruct<Struct_1>(p0);
        }
        public void Write_1(Struct_2 p0)
        {
            WriteStruct<Struct_2>(p0);
        }
        public void Write_2(Struct_3 p0)
        {
            WriteStruct<Struct_3>(p0);
        }
        public void Write_3(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_4(string p0)
        {
            WriteFixedString(p0, 128);
        }
        public void Write_5(string p0)
        {
            WriteFixedString(p0, 256);
        }
        public void Write_6(string[] p0, long p1)
        {
            WriteConformantStringArray(p0, new System.Action<string>(this.WriteTerminatedString), p1);
        }
        public void Write_7(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_8(System.Nullable<Struct_1>[] p0, long p1)
        {
            WriteConformantStructPointerArray<Struct_1>(p0, p1);
        }
        public void Write_9(string[] p0, long p1)
        {
            WriteConformantStringArray(p0, new System.Action<string>(this.WriteTerminatedString), p1);
        }
        public void Write_10(Struct_2[] p0, long p1)
        {
            WriteConformantStructArray<Struct_2>(p0, p1);
        }
        public void Write_11(System.Guid[] p0, long p1)
        {
            WriteConformantArrayCallback<System.Guid>(p0, new System.Action<System.Guid>(this.WriteGuid), p1);
        }
        public void Write_12(string[] p0, long p1)
        {
            WriteConformantStringArray(p0, new System.Action<string>(this.WriteTerminatedString), p1);
        }
        public void Write_13(Struct_3[] p0, long p1)
        {
            WriteConformantStructArray<Struct_3>(p0, p1);
        }
        public void Write_14(string[] p0, long p1)
        {
            WriteConformantStringArray(p0, new System.Action<string>(this.WriteTerminatedString), p1);
        }
    }
    internal class _Unmarshal_Helper : NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer
    {
        public _Unmarshal_Helper(NtApiDotNet.Win32.Rpc.RpcClientResponse r) : 
                base(r.NdrBuffer, r.Handles, r.DataRepresentation)
        {
        }
        public _Unmarshal_Helper(byte[] ba) : 
                base(ba)
        {
        }
        public Struct_1 Read_0()
        {
            return ReadStruct<Struct_1>();
        }
        public Struct_2 Read_1()
        {
            return ReadStruct<Struct_2>();
        }
        public Struct_3 Read_2()
        {
            return ReadStruct<Struct_3>();
        }
        public byte[] Read_3()
        {
            return ReadConformantArray<byte>();
        }
        public string Read_4()
        {
            return ReadFixedString(128);
        }
        public string Read_5()
        {
            return ReadFixedString(256);
        }
        public string[] Read_6()
        {
            return ReadConformantStringArray(new System.Func<string>(this.ReadConformantVaryingString));
        }
        public byte[] Read_7()
        {
            return ReadConformantArray<byte>();
        }
        public System.Nullable<Struct_1>[] Read_8()
        {
            return ReadConformantStructPointerArray<Struct_1>(false);
        }
        public string[] Read_9()
        {
            return ReadConformantStringArray(new System.Func<string>(this.ReadConformantVaryingString));
        }
        public Struct_2[] Read_10()
        {
            return ReadConformantStructArray<Struct_2>();
        }
        public System.Guid[] Read_11()
        {
            return ReadConformantArrayCallback<System.Guid>(new System.Func<System.Guid>(this.ReadGuid));
        }
        public string[] Read_12()
        {
            return ReadConformantStringArray(new System.Func<string>(this.ReadConformantVaryingString));
        }
        public Struct_3[] Read_13()
        {
            return ReadConformantStructArray<Struct_3>();
        }
        public string[] Read_14()
        {
            return ReadConformantStringArray(new System.Func<string>(this.ReadConformantVaryingString));
        }
    }
    #endregion
    #region Complex Types
    public struct Struct_1 : NtApiDotNet.Ndr.Marshal.INdrConformantStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt16(Member0);
            m.WriteInt16(Member2);
            m.WriteInt32(Member4);
            m.WriteInt32(Member8);
            m.WriteInt16(MemberC);
            m.WriteInt16(MemberE);
            m.WriteInt16(Member10);
            m.Write_3(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(Member12, "Member12"), Member10);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt16();
            Member2 = u.ReadInt16();
            Member4 = u.ReadInt32();
            Member8 = u.ReadInt32();
            MemberC = u.ReadInt16();
            MemberE = u.ReadInt16();
            Member10 = u.ReadInt16();
            Member12 = u.Read_3();
        }
        int NtApiDotNet.Ndr.Marshal.INdrConformantStructure.GetConformantDimensions()
        {
            return 1;
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public short Member0;
        public short Member2;
        public int Member4;
        public int Member8;
        public short MemberC;
        public short MemberE;
        public short Member10;
        public byte[] Member12;
        public static Struct_1 CreateDefault()
        {
            Struct_1 ret = new Struct_1();
            ret.Member12 = new byte[0];
            return ret;
        }
        public Struct_1(short Member0, short Member2, int Member4, int Member8, short MemberC, short MemberE, short Member10, byte[] Member12)
        {
            this.Member0 = Member0;
            this.Member2 = Member2;
            this.Member4 = Member4;
            this.Member8 = Member8;
            this.MemberC = MemberC;
            this.MemberE = MemberE;
            this.Member10 = Member10;
            this.Member12 = Member12;
        }
    }
    public struct Struct_2 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteGuid(Member0);
            m.WriteGuid(Member10);
            m.Write_4(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(Member20, "Member20"));
            m.Write_4(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(Member120, "Member120"));
            m.Write_5(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(Member220, "Member220"));
            m.Write_4(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(Member420, "Member420"));
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadGuid();
            Member10 = u.ReadGuid();
            Member20 = u.Read_4();
            Member120 = u.Read_4();
            Member220 = u.Read_5();
            Member420 = u.Read_4();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public System.Guid Member0;
        public System.Guid Member10;
        public string Member20;
        public string Member120;
        public string Member220;
        public string Member420;
        public static Struct_2 CreateDefault()
        {
            Struct_2 ret = new Struct_2();
            ret.Member20 = new string('\0', 128);
            ret.Member120 = new string('\0', 128);
            ret.Member220 = new string('\0', 256);
            ret.Member420 = new string('\0', 128);
            return ret;
        }
        public Struct_2(System.Guid Member0, System.Guid Member10, string Member20, string Member120, string Member220, string Member420)
        {
            this.Member0 = Member0;
            this.Member10 = Member10;
            this.Member20 = Member20;
            this.Member120 = Member120;
            this.Member220 = Member220;
            this.Member420 = Member420;
        }
    }
    public struct Struct_3 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteGuid(Member0);
            m.WriteEmbeddedPointer<string>(Member10, new System.Action<string>(m.WriteTerminatedString));
            m.WriteInt32(Member18);
            m.WriteEmbeddedPointer<string[], long>(Member20, new System.Action<string[], long>(m.Write_6), Member18);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadGuid();
            Member10 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member18 = u.ReadInt32();
            Member20 = u.ReadEmbeddedPointer<string[]>(new System.Func<string[]>(u.Read_6), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public System.Guid Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member10;
        public int Member18;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string[]> Member20;
        public static Struct_3 CreateDefault()
        {
            return new Struct_3();
        }
        public Struct_3(System.Guid Member0, string Member10, int Member18, string[] Member20)
        {
            this.Member0 = Member0;
            this.Member10 = Member10;
            this.Member18 = Member18;
            this.Member20 = Member20;
        }
    }
    #endregion
    #region Client Implementation
    public sealed class Client : NtApiDotNet.Win32.Rpc.RpcClientBase
    {
        public Client() : 
                base("923f85b3-bbee-4edf-8059-f569fa64a027", 1, 6)
        {
        }
        private _Unmarshal_Helper SendReceive(int p, _Marshal_Helper m)
        {
            return new _Unmarshal_Helper(SendReceive(p, m.DataRepresentation, m.ToArray(), m.Handles));
        }
        public int s_winmmGetPnpInfo(out int p0, out byte[] p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(0, m);
            p0 = u.ReadInt32();
            p1 = u.ReadReferent<byte[]>(new System.Func<byte[]>(u.Read_7), false);
            return u.ReadInt32();
        }
        public int s_mmeNotifyDeviceStateChanged(string p0, int p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteInt32(p1);
            _Unmarshal_Helper u = SendReceive(1, m);
            return u.ReadInt32();
        }
        public int s_mmeNotifyDeviceAdded(string p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            _Unmarshal_Helper u = SendReceive(2, m);
            return u.ReadInt32();
        }
        public int s_mmeNotifyDeviceRemoved(string p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            _Unmarshal_Helper u = SendReceive(3, m);
            return u.ReadInt32();
        }
        public int s_mmeNotifyDefaultDeviceChanged(int p0, int p1, string p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteInt32(p0);
            m.WriteInt32(p1);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"));
            _Unmarshal_Helper u = SendReceive(4, m);
            return u.ReadInt32();
        }
        public int s_tsSessionGetAudioProtocol(int p0, out int p1, out int p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteInt32(p0);
            _Unmarshal_Helper u = SendReceive(5, m);
            p1 = u.ReadInt32();
            p2 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int s_tsRegisterAudioProtocolNotification(out NtApiDotNet.Ndr.Marshal.NdrContextHandle p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(6, m);
            p0 = u.ReadContextHandle();
            return u.ReadInt32();
        }
        public int s_tsUnregisterAudioProtocolNotification(ref NtApiDotNet.Ndr.Marshal.NdrContextHandle p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(7, m);
            p0 = u.ReadContextHandle();
            return u.ReadInt32();
        }
        public int s_sndevtResolveSoundAlias(string p0, string p1, int p2, out NtApiDotNet.Ndr.Marshal.NdrInt3264 p3, ref string p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteReferent(p1, new System.Action<string>(m.WriteTerminatedString));
            m.WriteInt32(p2);
            m.WriteReferent(p4, new System.Action<string>(m.WriteTerminatedString));
            _Unmarshal_Helper u = SendReceive(8, m);
            p3 = u.ReadInt3264();
            p4 = u.ReadReferent<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            return u.ReadInt32();
        }
        public int s_pbmRegisterPlaybackManagerNotifications(NtApiDotNet.Ndr.Marshal.NdrEnum16 p0, NtApiDotNet.Ndr.Marshal.NdrEnum16 p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteEnum16(p0);
            m.WriteEnum16(p1);
            _Unmarshal_Helper u = SendReceive(9, m);
            return u.ReadInt32();
        }
        public int s_pbmUnregisterPlaybackManagerNotifications(NtApiDotNet.Ndr.Marshal.NdrEnum16 p0, NtApiDotNet.Ndr.Marshal.NdrEnum16 p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteEnum16(p0);
            m.WriteEnum16(p1);
            _Unmarshal_Helper u = SendReceive(10, m);
            return u.ReadInt32();
        }
        public int s_pbmSetSmtcSubscriptionState(NtApiDotNet.Ndr.Marshal.NdrEnum16 p0, int p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteEnum16(p0);
            m.WriteInt32(p1);
            _Unmarshal_Helper u = SendReceive(11, m);
            return u.ReadInt32();
        }
        public int s_pbmGetSoundLevel(System.Nullable<NtApiDotNet.Ndr.Marshal.NdrEnum16> p0, System.Nullable<NtApiDotNet.Ndr.Marshal.NdrEnum16> p1, string p2, out NtApiDotNet.Ndr.Marshal.NdrEnum16 p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteReferent(p0, new System.Action<NtApiDotNet.Ndr.Marshal.NdrEnum16>(m.WriteEnum16));
            m.WriteReferent(p1, new System.Action<NtApiDotNet.Ndr.Marshal.NdrEnum16>(m.WriteEnum16));
            m.WriteReferent(p2, new System.Action<string>(m.WriteTerminatedString));
            _Unmarshal_Helper u = SendReceive(12, m);
            p3 = u.ReadEnum16();
            return u.ReadInt32();
        }
        public int s_ccCreateHandsfreeHidFileFromAudioId(string p0, out int p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            _Unmarshal_Helper u = SendReceive(13, m);
            p1 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int s_pbmRegisterAppClosureNotification()
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(14, m);
            return u.ReadInt32();
        }
        public int s_pbmUnregisterAppClosureNotification()
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(15, m);
            return u.ReadInt32();
        }
        public int s_pbmPlayToStreamStateChanged(NtApiDotNet.Ndr.Marshal.NdrEnum16 p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteEnum16(p0);
            _Unmarshal_Helper u = SendReceive(16, m);
            return u.ReadInt32();
        }
        public int s_pbmIsPlaying(out int p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(17, m);
            p0 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int s_pbmCastingAppStateChanged(NtApiDotNet.Ndr.Marshal.NdrEnum16 p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteEnum16(p0);
            _Unmarshal_Helper u = SendReceive(18, m);
            return u.ReadInt32();
        }
        public int s_pbmVoipCallStateChanged(NtApiDotNet.Ndr.Marshal.NdrEnum16 p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteEnum16(p0);
            _Unmarshal_Helper u = SendReceive(19, m);
            return u.ReadInt32();
        }
        public int s_pbmLaunchBackgroundTask(string p0, string p1, out System.Guid p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            _Unmarshal_Helper u = SendReceive(20, m);
            p2 = u.ReadGuid();
            return u.ReadInt32();
        }
        public int s_pbmRegisterAsBackgroundTask(System.Guid p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            _Unmarshal_Helper u = SendReceive(21, m);
            return u.ReadInt32();
        }
        public int s_afxOpenAudioEffectsWatcher(string p0, NtApiDotNet.Ndr.Marshal.NdrEnum16 p1, int p2, out System.Guid p3, out long p4, out NtApiDotNet.Ndr.Marshal.NdrContextHandle p5)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteEnum16(p1);
            m.WriteInt32(p2);
            _Unmarshal_Helper u = SendReceive(22, m);
            p3 = u.ReadGuid();
            p4 = u.ReadInt64();
            p5 = u.ReadContextHandle();
            return u.ReadInt32();
        }
        public void s_afxCloseAudioEffectsWatcher(ref NtApiDotNet.Ndr.Marshal.NdrContextHandle p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(23, m);
            p0 = u.ReadContextHandle();
        }
        public int s_midiOpenPort(string p0, out NtApiDotNet.Ndr.Marshal.NdrUInt3264 p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            _Unmarshal_Helper u = SendReceive(24, m);
            p1 = u.ReadUInt3264();
            return u.ReadInt32();
        }
        public int s_rtgGetDefaultAudioEndpoint(NtApiDotNet.Ndr.Marshal.NdrEnum16 p0, NtApiDotNet.Ndr.Marshal.NdrEnum16 p1, out string p2, out int p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteEnum16(p0);
            m.WriteEnum16(p1);
            _Unmarshal_Helper u = SendReceive(25, m);
            p2 = u.ReadReferent<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            p3 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int s_apmRegisterProxyAudioProcess()
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(26, m);
            return u.ReadInt32();
        }
        public int s_apmSetDuckingGainForId(string p0, float p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteFloat(p1);
            _Unmarshal_Helper u = SendReceive(27, m);
            return u.ReadInt32();
        }
        public int s_apmSetLayoutGainForId(int p0, float p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteInt32(p0);
            m.WriteFloat(p1);
            _Unmarshal_Helper u = SendReceive(28, m);
            return u.ReadInt32();
        }
        public int s_apmSetVolumeGroupGainForId(string p0, float p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteFloat(p1);
            _Unmarshal_Helper u = SendReceive(29, m);
            return u.ReadInt32();
        }
        public int s_apmSetVolumeGroupGainScalarForId(string p0, string p1, float p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            m.WriteFloat(p2);
            _Unmarshal_Helper u = SendReceive(30, m);
            return u.ReadInt32();
        }
        public int s_apmSetVolumeGroupMuteForId(string p0, string p1, int p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            m.WriteInt32(p2);
            _Unmarshal_Helper u = SendReceive(31, m);
            return u.ReadInt32();
        }
        public int s_setRingerVibrateState(NtApiDotNet.Ndr.Marshal.NdrEnum16 p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteEnum16(p0);
            _Unmarshal_Helper u = SendReceive(32, m);
            return u.ReadInt32();
        }
        public int s_getRingerVibrateState(out NtApiDotNet.Ndr.Marshal.NdrEnum16 p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(33, m);
            p0 = u.ReadEnum16();
            return u.ReadInt32();
        }
        public int s_getEmergencyCallbackMode(out int p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(34, m);
            p0 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int s_setEmergencyCallbackMode(int p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteInt32(p0);
            _Unmarshal_Helper u = SendReceive(35, m);
            return u.ReadInt32();
        }
        public int s_apmSetPersistedDefaultAudioEndpoint(int p0, NtApiDotNet.Ndr.Marshal.NdrEnum16 p1, NtApiDotNet.Ndr.Marshal.NdrEnum16 p2, string p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteInt32(p0);
            m.WriteEnum16(p1);
            m.WriteEnum16(p2);
            m.WriteReferent(p3, new System.Action<string>(m.WriteTerminatedString));
            _Unmarshal_Helper u = SendReceive(36, m);
            return u.ReadInt32();
        }
        public int s_apmGetPersistedDefaultAudioEndpoint(int p0, NtApiDotNet.Ndr.Marshal.NdrEnum16 p1, NtApiDotNet.Ndr.Marshal.NdrEnum16 p2, out string p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteInt32(p0);
            m.WriteEnum16(p1);
            m.WriteEnum16(p2);
            _Unmarshal_Helper u = SendReceive(37, m);
            p3 = u.ReadReferent<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            return u.ReadInt32();
        }
        public int s_apmClearAllPersistedApplicationDefaultEndpoints()
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(38, m);
            return u.ReadInt32();
        }
        public int s_apmRegisterAudioStateMonitor(System.Nullable<NtApiDotNet.Ndr.Marshal.NdrEnum16> p0, System.Nullable<NtApiDotNet.Ndr.Marshal.NdrEnum16> p1, string p2, out long p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteReferent(p0, new System.Action<NtApiDotNet.Ndr.Marshal.NdrEnum16>(m.WriteEnum16));
            m.WriteReferent(p1, new System.Action<NtApiDotNet.Ndr.Marshal.NdrEnum16>(m.WriteEnum16));
            m.WriteReferent(p2, new System.Action<string>(m.WriteTerminatedString));
            _Unmarshal_Helper u = SendReceive(39, m);
            p3 = u.ReadInt64();
            return u.ReadInt32();
        }
        public int s_apmUnregisterAudioStateMonitor(ref long p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteInt64(p0);
            _Unmarshal_Helper u = SendReceive(40, m);
            p0 = u.ReadInt64();
            return u.ReadInt32();
        }
        public int s_apmHandleEuVolumeNotificationResponse(string p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            _Unmarshal_Helper u = SendReceive(41, m);
            return u.ReadInt32();
        }
        public int s_StartPersonalAssistantDialogSession(string p0, out NtApiDotNet.Ndr.Marshal.NdrContextHandle p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            _Unmarshal_Helper u = SendReceive(42, m);
            p1 = u.ReadContextHandle();
            return u.ReadInt32();
        }
        public int s_StopPersonalAssistantDialogSession(ref NtApiDotNet.Ndr.Marshal.NdrContextHandle p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(43, m);
            p0 = u.ReadContextHandle();
            return u.ReadInt32();
        }
        public int s_apmSetBalanceGroupBalanceForId(string p0, float p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteFloat(p1);
            _Unmarshal_Helper u = SendReceive(44, m);
            return u.ReadInt32();
        }
        public int s_apmSetPreferredChatApplication(string p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            _Unmarshal_Helper u = SendReceive(45, m);
            return u.ReadInt32();
        }
        public int s_apmResetPreferredChatApplication()
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(46, m);
            return u.ReadInt32();
        }
        public int s_CreateHolographicDisplay(out NtApiDotNet.Ndr.Marshal.NdrContextHandle p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(47, m);
            p0 = u.ReadContextHandle();
            return u.ReadInt32();
        }
        public int s_DestroyHolographicDisplay(ref NtApiDotNet.Ndr.Marshal.NdrContextHandle p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(48, m);
            p0 = u.ReadContextHandle();
            return u.ReadInt32();
        }
        public int s_GetHeadRotation(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, out float p1, out float p2, out float p3, out float p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(49, m);
            p1 = u.ReadFloat();
            p2 = u.ReadFloat();
            p3 = u.ReadFloat();
            p4 = u.ReadFloat();
            return u.ReadInt32();
        }
        public int s_GetCustomDeviceFormatsSupportedOnEndpoint(string p0, out int p1, out System.Nullable<Struct_1>[] p2, out string[] p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            _Unmarshal_Helper u = SendReceive(50, m);
            p1 = u.ReadInt32();
            p2 = u.ReadReferent<System.Nullable<Struct_1>[]>(new System.Func<System.Nullable<Struct_1>[]>(u.Read_8), false);
            p3 = u.ReadReferent<string[]>(new System.Func<string[]>(u.Read_9), false);
            return u.ReadInt32();
        }
        public int s_EndpointHasThirdPartySystemEffects(string p0, out int p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            _Unmarshal_Helper u = SendReceive(51, m);
            p1 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int s_IsProcessingModeSupportedOnHostConnector(string p0, System.Guid p1, out int p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteGuid(p1);
            _Unmarshal_Helper u = SendReceive(52, m);
            p2 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int s_apmDoesPlatformSupportVolumeGroups(out int p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(53, m);
            p0 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int s_epmGetCurrentEffectPackDescriptorForEndpoint(string p0, out Struct_2 p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            _Unmarshal_Helper u = SendReceive(54, m);
            p1 = u.Read_1();
            return u.ReadInt32();
        }
        public int s_epmSetCurrentEffectPackForEndpoint(string p0, System.Guid p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteGuid(p1);
            _Unmarshal_Helper u = SendReceive(55, m);
            return u.ReadInt32();
        }
        public int s_epmGetEffectPackDescriptorsForEndpoint(string p0, out Struct_2[] p1, out int p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            _Unmarshal_Helper u = SendReceive(56, m);
            p1 = u.ReadReferent<Struct_2[]>(new System.Func<Struct_2[]>(u.Read_10), false);
            p2 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int s_GetMulticastProviders(out System.Guid[] p0, out int p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(57, m);
            p0 = u.ReadReferent<System.Guid[]>(new System.Func<System.Guid[]>(u.Read_11), false);
            p1 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int s_GetMulticastCapableChildEndpoints(out string[] p0, out int p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(58, m);
            p0 = u.ReadReferent<string[]>(new System.Func<string[]>(u.Read_12), false);
            p1 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int s_GetMulticastSessions(out Struct_3[] p0, out int p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(59, m);
            p0 = u.ReadReferent<Struct_3[]>(new System.Func<Struct_3[]>(u.Read_13), false);
            p1 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int s_ActivateMulticastSession(string[] p0, int p1, System.Guid p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.Write_14(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"), p1);
            m.WriteInt32(p1);
            m.WriteGuid(p2);
            _Unmarshal_Helper u = SendReceive(60, m);
            return u.ReadInt32();
        }
        public int s_DeactivateMulticastSession(System.Guid p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteGuid(p0);
            _Unmarshal_Helper u = SendReceive(61, m);
            return u.ReadInt32();
        }
    }
    #endregion
}

