//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Source Executable: c:\windows\system32\psmserviceexthost.dll
// Interface ID: 95406f0b-b239-4318-91bb-cea3a46ff0dc
// Interface Version: 1.0
// Client Generated: 3/4/2026 7:38:14 PM
// NtApiDotNet Version: 1.1.33

namespace rpc_95406f0b_b239_4318_91bb_cea3a46ff0dc_1_0
{
    
    #region Marshal Helpers
    internal class _Marshal_Helper : NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer
    {
        public void Write_0(Struct_0 p0)
        {
            WriteStruct<Struct_0>(p0);
        }
        public void Write_1(Struct_1 p0)
        {
            WriteStruct<Struct_1>(p0);
        }
        public void Write_2(Struct_2 p0)
        {
            WriteStruct<Struct_2>(p0);
        }
        public void Write_3(Struct_3 p0)
        {
            WriteStruct<Struct_3>(p0);
        }
        public void Write_4(string p0)
        {
            WriteFixedString(p0, 232);
        }
        public void Write_5(byte[] p0)
        {
            WriteFixedByteArray(p0, 68);
        }
        public void Write_6(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_7(string[] p0, long p1)
        {
            WriteConformantStringArray(p0, new System.Action<string>(this.WriteTerminatedString), p1);
        }
        public void Write_8(Struct_0[] p0, long p1)
        {
            WriteConformantStructArray<Struct_0>(p0, p1);
        }
        public void Write_9(NtApiDotNet.NtProcess p0)
        {
            WriteSystemHandle<NtApiDotNet.NtProcess>(p0);
        }
        public void Write_10(NtApiDotNet.NtProcess[] p0, long p1)
        {
            WriteConformantArrayCallback<NtApiDotNet.NtProcess>(p0, new System.Action<NtApiDotNet.NtProcess>(this.Write_9), p1);
        }
    }
    internal class _Unmarshal_Helper : NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer
    {
        public _Unmarshal_Helper(NtApiDotNet.Win32.Rpc.RpcClientResponse r) : 
                base(r.NdrBuffer, r.Handles, r.DataRepresentation)
        {
        }
        public _Unmarshal_Helper(byte[] ba) : 
                base(ba)
        {
        }
        public Struct_0 Read_0()
        {
            return ReadStruct<Struct_0>();
        }
        public Struct_1 Read_1()
        {
            return ReadStruct<Struct_1>();
        }
        public Struct_2 Read_2()
        {
            return ReadStruct<Struct_2>();
        }
        public Struct_3 Read_3()
        {
            return ReadStruct<Struct_3>();
        }
        public string Read_4()
        {
            return ReadFixedString(232);
        }
        public byte[] Read_5()
        {
            return ReadFixedByteArray(68);
        }
        public byte[] Read_6()
        {
            return ReadConformantArray<byte>();
        }
        public string[] Read_7()
        {
            return ReadConformantStringArray(new System.Func<string>(this.ReadConformantVaryingString));
        }
        public Struct_0[] Read_8()
        {
            return ReadConformantStructArray<Struct_0>();
        }
        public NtApiDotNet.NtProcess Read_9()
        {
            return ReadSystemHandle<NtApiDotNet.NtProcess>();
        }
        public NtApiDotNet.NtProcess[] Read_10()
        {
            return ReadConformantArrayCallback<NtApiDotNet.NtProcess>(new System.Func<NtApiDotNet.NtProcess>(this.Read_9));
        }
    }
    #endregion
    #region Complex Types
    public struct Struct_0 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt64(Member0);
            m.WriteInt32(Member8);
            m.WriteInt32(MemberC);
            m.Write_1(Member10);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt64();
            Member8 = u.ReadInt32();
            MemberC = u.ReadInt32();
            Member10 = u.Read_1();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public long Member0;
        public int Member8;
        public int MemberC;
        public Struct_1 Member10;
        public static Struct_0 CreateDefault()
        {
            return new Struct_0();
        }
        public Struct_0(long Member0, int Member8, int MemberC, Struct_1 Member10)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.MemberC = MemberC;
            this.Member10 = Member10;
        }
    }
    public struct Struct_1 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.Write_2(Member0);
            m.Write_3(Member1D0);
            m.WriteInt32(Member214);
            m.WriteInt32(Member218);
            m.WriteInt64(Member220);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.Read_2();
            Member1D0 = u.Read_3();
            Member214 = u.ReadInt32();
            Member218 = u.ReadInt32();
            Member220 = u.ReadInt64();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public Struct_2 Member0;
        public Struct_3 Member1D0;
        public int Member214;
        public int Member218;
        public long Member220;
        public static Struct_1 CreateDefault()
        {
            return new Struct_1();
        }
        public Struct_1(Struct_2 Member0, Struct_3 Member1D0, int Member214, int Member218, long Member220)
        {
            this.Member0 = Member0;
            this.Member1D0 = Member1D0;
            this.Member214 = Member214;
            this.Member218 = Member218;
            this.Member220 = Member220;
        }
    }
    public struct Struct_2 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.Write_4(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(Member0, "Member0"));
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.Read_4();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 2;
        }
        public string Member0;
        public static Struct_2 CreateDefault()
        {
            Struct_2 ret = new Struct_2();
            ret.Member0 = new string('\0', 232);
            return ret;
        }
        public Struct_2(string Member0)
        {
            this.Member0 = Member0;
        }
    }
    public struct Struct_3 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.Write_5(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(Member0, "Member0"));
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.Read_5();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 1;
        }
        public byte[] Member0;
        public static Struct_3 CreateDefault()
        {
            Struct_3 ret = new Struct_3();
            ret.Member0 = new byte[68];
            return ret;
        }
        public Struct_3(byte[] Member0)
        {
            this.Member0 = Member0;
        }
    }
    #endregion
    #region Client Implementation
    public sealed class Client : NtApiDotNet.Win32.Rpc.RpcClientBase
    {
        public Client() : 
                base("95406f0b-b239-4318-91bb-cea3a46ff0dc", 1, 0)
        {
        }
        private _Unmarshal_Helper SendReceive(int p, _Marshal_Helper m)
        {
            return new _Unmarshal_Helper(SendReceive(p, m.DataRepresentation, m.ToArray(), m.Handles));
        }
        public uint HamRpcSrvConnectServicing(out NtApiDotNet.Ndr.Marshal.NdrContextHandle p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(0, m);
            p0 = u.ReadContextHandle();
            return u.ReadUInt32();
        }
        public uint HamRpcSrvDisconnect(ref NtApiDotNet.Ndr.Marshal.NdrContextHandle p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(1, m);
            p0 = u.ReadContextHandle();
            return u.ReadUInt32();
        }
        public uint HamRpcSrvFullTrustOpenPackageHandle(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, string p1, int p2, byte[] p3, int p4, out long p5)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            m.WriteInt32(p2);
            m.Write_6(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p3, "p3"), p4);
            m.WriteInt32(p4);
            _Unmarshal_Helper u = SendReceive(2, m);
            p5 = u.ReadInt64();
            return u.ReadUInt32();
        }
        public uint HamRpcSrvDebugClosePackageHandle(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, long p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt64(p1);
            _Unmarshal_Helper u = SendReceive(3, m);
            return u.ReadUInt32();
        }
        public uint HamRpcSrvServicingQueryActiveAppsInPackage(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, long p1, int p2, out string[] p3, out int p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt64(p1);
            m.WriteInt32(p2);
            _Unmarshal_Helper u = SendReceive(4, m);
            p3 = u.ReadReferent<string[]>(new System.Func<string[]>(u.Read_7), false);
            p4 = u.ReadInt32();
            return u.ReadUInt32();
        }
        public uint HamRpcSrvDebugQueryPackageState(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, long p1, out int p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt64(p1);
            _Unmarshal_Helper u = SendReceive(5, m);
            p2 = u.ReadInt32();
            return u.ReadUInt32();
        }
        public uint HamRpcSrvDebugQueryPackageStateEx(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, long p1, out int p2, out Struct_0[] p3, out int p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt64(p1);
            _Unmarshal_Helper u = SendReceive(6, m);
            p2 = u.ReadInt32();
            p3 = u.ReadReferent<Struct_0[]>(new System.Func<Struct_0[]>(u.Read_8), false);
            p4 = u.ReadInt32();
            return u.ReadUInt32();
        }
        public uint HamRpcSrvServicingEnableServicing(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, long p1, int p2, out NtApiDotNet.NtProcess[] p3, out int p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt64(p1);
            m.WriteInt32(p2);
            _Unmarshal_Helper u = SendReceive(7, m);
            p3 = u.ReadReferent<NtApiDotNet.NtProcess[]>(new System.Func<NtApiDotNet.NtProcess[]>(u.Read_10), false);
            p4 = u.ReadInt32();
            return u.ReadUInt32();
        }
        public uint HamRpcSrvDebugTerminatePackage(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, long p1, NtApiDotNet.Ndr.Marshal.NdrEnum16 p2, NtApiDotNet.Ndr.Marshal.NdrEnum16 p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt64(p1);
            m.WriteEnum16(p2);
            m.WriteEnum16(p3);
            _Unmarshal_Helper u = SendReceive(8, m);
            return u.ReadUInt32();
        }
    }
    #endregion
}

