//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Source Executable: c:\windows\system32\rpcss.dll
// Interface ID: b9e79e60-3d52-11ce-aaa1-00006901293f
// Interface Version: 0.2
// Client Generated: 3/4/2026 7:38:18 PM
// NtApiDotNet Version: 1.1.33

namespace rpc_b9e79e60_3d52_11ce_aaa1_00006901293f_0_2
{
    
    #region Marshal Helpers
    internal class _Marshal_Helper : NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer
    {
        public void Write_0(Struct_0 p0)
        {
            WriteStruct<Struct_0>(p0);
        }
        public void Write_1(Struct_1 p0)
        {
            WriteStruct<Struct_1>(p0);
        }
        public void Write_2(Struct_2 p0)
        {
            WriteStruct<Struct_2>(p0);
        }
        public void Write_3(Struct_3 p0)
        {
            WriteStruct<Struct_3>(p0);
        }
        public void Write_4(Struct_4 p0)
        {
            WriteStruct<Struct_4>(p0);
        }
        public void Write_5(Struct_5 p0)
        {
            WriteStruct<Struct_5>(p0);
        }
        public void Write_6(Struct_6 p0)
        {
            WriteStruct<Struct_6>(p0);
        }
        public void Write_7(Struct_8 p0)
        {
            WriteStruct<Struct_8>(p0);
        }
        public void Write_8(Struct_9 p0)
        {
            WriteStruct<Struct_9>(p0);
        }
        public void Write_9(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_10(byte[] p0, long p1)
        {
            WriteVaryingArray<byte>(p0, p1);
        }
        public void Write_11(short[] p0, long p1)
        {
            WriteConformantArray<short>(p0, p1);
        }
        public void Write_12(Struct_6[] p0, long p1)
        {
            WriteConformantStructArray<Struct_6>(p0, p1);
        }
        public void Write_13(System.Nullable<Struct_0>[] p0, long p1)
        {
            WriteConformantStructPointerArray<Struct_0>(p0, p1);
        }
        public void Write_14(NtApiDotNet.Ndr.Marshal.NdrUnsupported p0)
        {
            WriteUnsupported(p0, "FC_BOGUS_ARRAY -  HSTRING[]");
        }
        public void Write_15(NtApiDotNet.Ndr.Marshal.NdrUnsupported p0)
        {
            WriteUnsupported(p0, "FC_BOGUS_ARRAY -  HSTRING[]");
        }
        public void Write_16(NtApiDotNet.Ndr.Marshal.NdrUnsupported p0)
        {
            WriteUnsupported(p0, "FC_BOGUS_ARRAY -  HSTRING[]");
        }
        public void Write_17(NtApiDotNet.Ndr.Marshal.NdrUnsupported p0)
        {
            WriteUnsupported(p0, "FC_BOGUS_ARRAY -  HSTRING[]");
        }
        public void Write_18(NtApiDotNet.Ndr.Marshal.NdrUnsupported p0)
        {
            WriteUnsupported(p0, "FC_BOGUS_ARRAY -  HSTRING[]");
        }
        public void Write_19(NtApiDotNet.Ndr.Marshal.NdrUnsupported p0)
        {
            WriteUnsupported(p0, "FC_BOGUS_ARRAY -  HSTRING[]");
        }
    }
    internal class _Unmarshal_Helper : NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer
    {
        public _Unmarshal_Helper(NtApiDotNet.Win32.Rpc.RpcClientResponse r) : 
                base(r.NdrBuffer, r.Handles, r.DataRepresentation)
        {
        }
        public _Unmarshal_Helper(byte[] ba) : 
                base(ba)
        {
        }
        public Struct_0 Read_0()
        {
            return ReadStruct<Struct_0>();
        }
        public Struct_1 Read_1()
        {
            return ReadStruct<Struct_1>();
        }
        public Struct_2 Read_2()
        {
            return ReadStruct<Struct_2>();
        }
        public Struct_3 Read_3()
        {
            return ReadStruct<Struct_3>();
        }
        public Struct_4 Read_4()
        {
            return ReadStruct<Struct_4>();
        }
        public Struct_5 Read_5()
        {
            return ReadStruct<Struct_5>();
        }
        public Struct_6 Read_6()
        {
            return ReadStruct<Struct_6>();
        }
        public Struct_8 Read_7()
        {
            return ReadStruct<Struct_8>();
        }
        public Struct_9 Read_8()
        {
            return ReadStruct<Struct_9>();
        }
        public byte[] Read_9()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_10()
        {
            return ReadVaryingArray<byte>();
        }
        public short[] Read_11()
        {
            return ReadConformantArray<short>();
        }
        public Struct_6[] Read_12()
        {
            return ReadConformantStructArray<Struct_6>();
        }
        public System.Nullable<Struct_0>[] Read_13()
        {
            return ReadConformantStructPointerArray<Struct_0>(false);
        }
        public NtApiDotNet.Ndr.Marshal.NdrUnsupported Read_14()
        {
            return ReadUnsupported("FC_BOGUS_ARRAY -  HSTRING[]");
        }
        public NtApiDotNet.Ndr.Marshal.NdrUnsupported Read_15()
        {
            return ReadUnsupported("FC_BOGUS_ARRAY -  HSTRING[]");
        }
        public NtApiDotNet.Ndr.Marshal.NdrUnsupported Read_16()
        {
            return ReadUnsupported("FC_BOGUS_ARRAY -  HSTRING[]");
        }
        public NtApiDotNet.Ndr.Marshal.NdrUnsupported Read_17()
        {
            return ReadUnsupported("FC_BOGUS_ARRAY -  HSTRING[]");
        }
        public NtApiDotNet.Ndr.Marshal.NdrUnsupported Read_18()
        {
            return ReadUnsupported("FC_BOGUS_ARRAY -  HSTRING[]");
        }
        public NtApiDotNet.Ndr.Marshal.NdrUnsupported Read_19()
        {
            return ReadUnsupported("FC_BOGUS_ARRAY -  HSTRING[]");
        }
    }
    #endregion
    #region Complex Types
    public struct Struct_0 : NtApiDotNet.Ndr.Marshal.INdrConformantStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.Write_9(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(Member4, "Member4"), Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member4 = u.Read_9();
        }
        int NtApiDotNet.Ndr.Marshal.INdrConformantStructure.GetConformantDimensions()
        {
            return 1;
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public byte[] Member4;
        public static Struct_0 CreateDefault()
        {
            Struct_0 ret = new Struct_0();
            ret.Member4 = new byte[0];
            return ret;
        }
        public Struct_0(int Member0, byte[] Member4)
        {
            this.Member0 = Member0;
            this.Member4 = Member4;
        }
    }
    public struct Struct_1 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.Write_10(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(Member4, "Member4"), Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member4 = u.Read_10();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public byte[] Member4;
        public static Struct_1 CreateDefault()
        {
            Struct_1 ret = new Struct_1();
            ret.Member4 = new byte[0];
            return ret;
        }
        public Struct_1(int Member0, byte[] Member4)
        {
            this.Member0 = Member0;
            this.Member4 = Member4;
        }
    }
    public struct Struct_2 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteInt32(Member4);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member4 = u.ReadInt32();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public int Member4;
        public static Struct_2 CreateDefault()
        {
            return new Struct_2();
        }
        public Struct_2(int Member0, int Member4)
        {
            this.Member0 = Member0;
            this.Member4 = Member4;
        }
    }
    public struct Struct_3 : NtApiDotNet.Ndr.Marshal.INdrConformantStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteInt32(Member4);
            m.Write_11(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(Member8, "Member8"), Member4);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member4 = u.ReadInt32();
            Member8 = u.Read_11();
        }
        int NtApiDotNet.Ndr.Marshal.INdrConformantStructure.GetConformantDimensions()
        {
            return 1;
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public int Member4;
        public short[] Member8;
        public static Struct_3 CreateDefault()
        {
            Struct_3 ret = new Struct_3();
            ret.Member8 = new short[0];
            return ret;
        }
        public Struct_3(int Member0, int Member4, short[] Member8)
        {
            this.Member0 = Member0;
            this.Member4 = Member4;
            this.Member8 = Member8;
        }
    }
    public struct Struct_4 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt64(Member0);
            m.WriteInt32(Member8);
            m.WriteInt32(MemberC);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt64();
            Member8 = u.ReadInt32();
            MemberC = u.ReadInt32();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public long Member0;
        public int Member8;
        public int MemberC;
        public static Struct_4 CreateDefault()
        {
            return new Struct_4();
        }
        public Struct_4(long Member0, int Member8, int MemberC)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.MemberC = MemberC;
        }
    }
    public struct Struct_5 : NtApiDotNet.Ndr.Marshal.INdrConformantStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.Write_12(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(Member8, "Member8"), Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.Read_12();
        }
        int NtApiDotNet.Ndr.Marshal.INdrConformantStructure.GetConformantDimensions()
        {
            return 1;
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public Struct_6[] Member8;
        public static Struct_5 CreateDefault()
        {
            Struct_5 ret = new Struct_5();
            ret.Member8 = new Struct_6[0];
            return ret;
        }
        public Struct_5(int Member0, Struct_6[] Member8)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
        }
    }
    public struct Struct_6 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteEmbeddedPointer<Struct_1>(Member0, new System.Action<Struct_1>(m.Write_1));
            m.WriteInt32(Member8);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadEmbeddedPointer<Struct_1>(new System.Func<Struct_1>(u.Read_1), false);
            Member8 = u.ReadInt32();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_1> Member0;
        public int Member8;
        public static Struct_6 CreateDefault()
        {
            return new Struct_6();
        }
        public Struct_6(System.Nullable<Struct_1> Member0, int Member8)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
        }
    }
    public struct Struct_8 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteGuid(Member0);
            m.Write_4(Member10);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadGuid();
            Member10 = u.Read_4();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public System.Guid Member0;
        public Struct_4 Member10;
        public static Struct_8 CreateDefault()
        {
            return new Struct_8();
        }
        public Struct_8(System.Guid Member0, Struct_4 Member10)
        {
            this.Member0 = Member0;
            this.Member10 = Member10;
        }
    }
    public struct Struct_9 : NtApiDotNet.Ndr.Marshal.INdrConformantStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.Write_13(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(Member8, "Member8"), Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.Read_13();
        }
        int NtApiDotNet.Ndr.Marshal.INdrConformantStructure.GetConformantDimensions()
        {
            return 1;
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public System.Nullable<Struct_0>[] Member8;
        public static Struct_9 CreateDefault()
        {
            Struct_9 ret = new Struct_9();
            ret.Member8 = new System.Nullable<Struct_0>[0];
            return ret;
        }
        public Struct_9(int Member0, System.Nullable<Struct_0>[] Member8)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
        }
    }
    #endregion
    #region Client Implementation
    public sealed class Client : NtApiDotNet.Win32.Rpc.RpcClientBase
    {
        public Client() : 
                base("b9e79e60-3d52-11ce-aaa1-00006901293f", 0, 2)
        {
        }
        private _Unmarshal_Helper SendReceive(int p, _Marshal_Helper m)
        {
            return new _Unmarshal_Helper(SendReceive(p, m.DataRepresentation, m.ToArray(), m.Handles));
        }
        public int IrotRegister(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, string p1, Struct_0 p2, Struct_1 p3, Struct_1 p4, Struct_2 p5, int p6, int p7, int p8, NtApiDotNet.Ndr.Marshal.NdrUnsupported p9, out Struct_4 p10, out uint p11)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteReferent(p1, new System.Action<string>(m.WriteTerminatedString));
            m.Write_0(p2);
            m.Write_1(p3);
            m.Write_1(p4);
            m.Write_2(p5);
            m.WriteInt32(p6);
            m.WriteInt32(p7);
            m.WriteInt32(p8);
            m.WriteReferent(p9, new System.Action<NtApiDotNet.Ndr.Marshal.NdrUnsupported>(m.Write_14));
            _Unmarshal_Helper u = SendReceive(0, m);
            p10 = u.Read_4();
            p11 = u.ReadUInt32();
            return u.ReadInt32();
        }
        public int IrotRevoke(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, Struct_4 p1, out System.Nullable<Struct_1> p2, out System.Nullable<Struct_1> p3, out int p4, out uint p5)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.Write_4(p1);
            _Unmarshal_Helper u = SendReceive(1, m);
            p2 = u.ReadReferentValue<Struct_1>(new System.Func<Struct_1>(u.Read_1), false);
            p3 = u.ReadReferentValue<Struct_1>(new System.Func<Struct_1>(u.Read_1), false);
            p4 = u.ReadInt32();
            p5 = u.ReadUInt32();
            return u.ReadInt32();
        }
        public int IrotIsRunning(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, string p1, Struct_0 p2, out uint p3, int p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteReferent(p1, new System.Action<string>(m.WriteTerminatedString));
            m.Write_0(p2);
            m.WriteInt32(p4);
            _Unmarshal_Helper u = SendReceive(2, m);
            p3 = u.ReadUInt32();
            return u.ReadInt32();
        }
        public int IrotGetObject(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, string p1, int p2, Struct_0 p3, out Struct_4 p4, out System.Nullable<Struct_1> p5, out int p6, out int p7, out uint p8, int p9)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteReferent(p1, new System.Action<string>(m.WriteTerminatedString));
            m.WriteInt32(p2);
            m.Write_0(p3);
            m.WriteInt32(p9);
            _Unmarshal_Helper u = SendReceive(3, m);
            p4 = u.Read_4();
            p5 = u.ReadReferentValue<Struct_1>(new System.Func<Struct_1>(u.Read_1), false);
            p6 = u.ReadInt32();
            p7 = u.ReadInt32();
            p8 = u.ReadUInt32();
            return u.ReadInt32();
        }
        public int IrotNoteChangeTime(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, Struct_4 p1, Struct_2 p2, out uint p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.Write_4(p1);
            m.Write_2(p2);
            _Unmarshal_Helper u = SendReceive(4, m);
            p3 = u.ReadUInt32();
            return u.ReadInt32();
        }
        public int IrotGetTimeOfLastChange(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, string p1, Struct_0 p2, out Struct_2 p3, out uint p4, int p5)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteReferent(p1, new System.Action<string>(m.WriteTerminatedString));
            m.Write_0(p2);
            m.WriteInt32(p5);
            _Unmarshal_Helper u = SendReceive(5, m);
            p3 = u.Read_2();
            p4 = u.ReadUInt32();
            return u.ReadInt32();
        }
        public int IrotEnumRunning(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, string p1, out System.Nullable<Struct_5> p2, out uint p3, int p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteReferent(p1, new System.Action<string>(m.WriteTerminatedString));
            m.WriteInt32(p4);
            _Unmarshal_Helper u = SendReceive(6, m);
            p2 = u.ReadReferentValue<Struct_5>(new System.Func<Struct_5>(u.Read_5), false);
            p3 = u.ReadUInt32();
            return u.ReadInt32();
        }
        public int IMgotRegister(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, NtApiDotNet.Ndr.Marshal.NdrEnum16 p1, string p2, System.Guid p3, int p4, NtApiDotNet.Ndr.Marshal.NdrUnsupported p5, Struct_0 p6, Struct_1 p7, int p8, out Struct_8 p9, out uint p10)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteEnum16(p1);
            m.WriteReferent(p2, new System.Action<string>(m.WriteTerminatedString));
            m.WriteGuid(p3);
            m.WriteInt32(p4);
            m.WriteReferent(p5, new System.Action<NtApiDotNet.Ndr.Marshal.NdrUnsupported>(m.Write_15));
            m.Write_0(p6);
            m.Write_1(p7);
            m.WriteInt32(p8);
            _Unmarshal_Helper u = SendReceive(7, m);
            p9 = u.Read_7();
            p10 = u.ReadUInt32();
            return u.ReadInt32();
        }
        public int IMgotRevoke(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, NtApiDotNet.Ndr.Marshal.NdrEnum16 p1, Struct_8 p2, out System.Nullable<Struct_1> p3, out int p4, out uint p5)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteEnum16(p1);
            m.Write_7(p2);
            _Unmarshal_Helper u = SendReceive(8, m);
            p3 = u.ReadReferentValue<Struct_1>(new System.Func<Struct_1>(u.Read_1), false);
            p4 = u.ReadInt32();
            p5 = u.ReadUInt32();
            return u.ReadInt32();
        }
        public int IMgotGetObject(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, NtApiDotNet.Ndr.Marshal.NdrEnum16 p1, string p2, System.Guid p3, int p4, NtApiDotNet.Ndr.Marshal.NdrUnsupported p5, int p6, NtApiDotNet.Ndr.Marshal.NdrUnsupported p7, Struct_0 p8, out System.Nullable<Struct_1> p9, out int p10, out int p11, out uint p12)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteEnum16(p1);
            m.WriteReferent(p2, new System.Action<string>(m.WriteTerminatedString));
            m.WriteGuid(p3);
            m.WriteInt32(p4);
            m.WriteReferent(p5, new System.Action<NtApiDotNet.Ndr.Marshal.NdrUnsupported>(m.Write_16));
            m.WriteInt32(p6);
            m.WriteReferent(p7, new System.Action<NtApiDotNet.Ndr.Marshal.NdrUnsupported>(m.Write_17));
            m.Write_0(p8);
            _Unmarshal_Helper u = SendReceive(9, m);
            p9 = u.ReadReferentValue<Struct_1>(new System.Func<Struct_1>(u.Read_1), false);
            p10 = u.ReadInt32();
            p11 = u.ReadInt32();
            p12 = u.ReadUInt32();
            return u.ReadInt32();
        }
        public int IMgotEnumRunning(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, string p1, System.Guid p2, int p3, NtApiDotNet.Ndr.Marshal.NdrUnsupported p4, int p5, NtApiDotNet.Ndr.Marshal.NdrUnsupported p6, out System.Nullable<Struct_9> p7, out uint p8)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteReferent(p1, new System.Action<string>(m.WriteTerminatedString));
            m.WriteGuid(p2);
            m.WriteInt32(p3);
            m.WriteReferent(p4, new System.Action<NtApiDotNet.Ndr.Marshal.NdrUnsupported>(m.Write_18));
            m.WriteInt32(p5);
            m.WriteReferent(p6, new System.Action<NtApiDotNet.Ndr.Marshal.NdrUnsupported>(m.Write_19));
            _Unmarshal_Helper u = SendReceive(10, m);
            p7 = u.ReadReferentValue<Struct_9>(new System.Func<Struct_9>(u.Read_8), false);
            p8 = u.ReadUInt32();
            return u.ReadInt32();
        }
    }
    #endregion
}

