//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Source Executable: c:\windows\system32\frameservermonitor.dll
// Interface ID: be0d95ba-21a5-4a5f-a1f0-9ada84ac1144
// Interface Version: 1.0
// Client Generated: 3/4/2026 7:37:26 PM
// NtApiDotNet Version: 1.1.33

namespace rpc_be0d95ba_21a5_4a5f_a1f0_9ada84ac1144_1_0
{
    
    #region Marshal Helpers
    internal class _Marshal_Helper : NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer
    {
        public void Write_0(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_1(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_2(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_3(NtApiDotNet.NtEvent p0)
        {
            WriteSystemHandle<NtApiDotNet.NtEvent>(p0);
        }
        public void Write_4(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_5(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_6(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_7(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_8(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_9(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_10(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_11(long[] p0, long p1)
        {
            WriteConformantArray<long>(p0, p1);
        }
        public void Write_12(long[] p0, long p1)
        {
            WriteConformantArray<long>(p0, p1);
        }
        public void Write_13(System.Guid[] p0, long p1)
        {
            WriteConformantArray<System.Guid>(p0, p1);
        }
        public void Write_14(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_15(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_16(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_17(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_18(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_19(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_20(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_21(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_22(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
    }
    internal class _Unmarshal_Helper : NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer
    {
        public _Unmarshal_Helper(NtApiDotNet.Win32.Rpc.RpcClientResponse r) : 
                base(r.NdrBuffer, r.Handles, r.DataRepresentation)
        {
        }
        public _Unmarshal_Helper(byte[] ba) : 
                base(ba)
        {
        }
        public byte[] Read_0()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_1()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_2()
        {
            return ReadConformantArray<byte>();
        }
        public NtApiDotNet.NtEvent Read_3()
        {
            return ReadSystemHandle<NtApiDotNet.NtEvent>();
        }
        public byte[] Read_4()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_5()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_6()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_7()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_8()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_9()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_10()
        {
            return ReadConformantArray<byte>();
        }
        public long[] Read_11()
        {
            return ReadConformantArray<long>();
        }
        public long[] Read_12()
        {
            return ReadConformantArray<long>();
        }
        public System.Guid[] Read_13()
        {
            return ReadConformantArray<System.Guid>();
        }
        public byte[] Read_14()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_15()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_16()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_17()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_18()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_19()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_20()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_21()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_22()
        {
            return ReadConformantArray<byte>();
        }
    }
    #endregion
    #region Client Implementation
    public sealed class Client : NtApiDotNet.Win32.Rpc.RpcClientBase
    {
        public Client() : 
                base("be0d95ba-21a5-4a5f-a1f0-9ada84ac1144", 1, 0)
        {
        }
        private _Unmarshal_Helper SendReceive(int p, _Marshal_Helper m)
        {
            return new _Unmarshal_Helper(SendReceive(p, m.DataRepresentation, m.ToArray(), m.Handles));
        }
        public int Server_FSMRegisterSession(NtApiDotNet.Ndr.Marshal.NdrEnum16 p0, string p1, byte[] p2, int p3, out NtApiDotNet.Ndr.Marshal.NdrContextHandle p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteEnum16(p0);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            m.WriteReferent(p2, new System.Action<byte[], long>(m.Write_0), p3);
            m.WriteInt32(p3);
            _Unmarshal_Helper u = SendReceive(0, m);
            p4 = u.ReadContextHandle();
            return u.ReadInt32();
        }
        public int Server_FSMUpdateSessionData(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, NtApiDotNet.Ndr.Marshal.NdrEnum16 p1, byte[] p2, int p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteEnum16(p1);
            m.WriteReferent(p2, new System.Action<byte[], long>(m.Write_1), p3);
            m.WriteInt32(p3);
            _Unmarshal_Helper u = SendReceive(1, m);
            return u.ReadInt32();
        }
        public int Server_FSMUnregisterSession(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, NtApiDotNet.Ndr.Marshal.NdrEnum16 p1, long p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteEnum16(p1);
            m.WriteInt64(p2);
            _Unmarshal_Helper u = SendReceive(2, m);
            return u.ReadInt32();
        }
        public int Server_FSMRegisterNotificationPublisher(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, string p1, byte[] p2, int p3, out long p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            m.WriteReferent(p2, new System.Action<byte[], long>(m.Write_2), p3);
            m.WriteInt32(p3);
            _Unmarshal_Helper u = SendReceive(3, m);
            p4 = u.ReadInt64();
            return u.ReadInt32();
        }
        public int Server_FSMRegisterNotificationConsumer(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, string p1, NtApiDotNet.NtEvent p2, byte[] p3, int p4, out long p5)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            m.Write_3(p2);
            m.WriteReferent(p3, new System.Action<byte[], long>(m.Write_4), p4);
            m.WriteInt32(p4);
            _Unmarshal_Helper u = SendReceive(4, m);
            p5 = u.ReadInt64();
            return u.ReadInt32();
        }
        public int Server_FSMEnqueueNotificationData(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, long p1, byte[] p2, int p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt64(p1);
            m.WriteReferent(p2, new System.Action<byte[], long>(m.Write_5), p3);
            m.WriteInt32(p3);
            _Unmarshal_Helper u = SendReceive(5, m);
            return u.ReadInt32();
        }
        public int Server_FSMDequeueNotificationDataSize(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, long p1, out int p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt64(p1);
            _Unmarshal_Helper u = SendReceive(6, m);
            p2 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int Server_FSMDequeueNotificationData(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, long p1, ref byte[] p2, int p3, out int p4, out int p5)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt64(p1);
            m.WriteReferent(p2, new System.Action<byte[], long>(m.Write_6), p3);
            m.WriteInt32(p3);
            _Unmarshal_Helper u = SendReceive(7, m);
            p2 = u.ReadReferent<byte[]>(new System.Func<byte[]>(u.Read_6), false);
            p4 = u.ReadInt32();
            p5 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int Server_FSMUnregisterNotificationPublisher(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, long p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt64(p1);
            _Unmarshal_Helper u = SendReceive(8, m);
            return u.ReadInt32();
        }
        public int Server_FSMUnregisterNotificationConsumer(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, long p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt64(p1);
            _Unmarshal_Helper u = SendReceive(9, m);
            return u.ReadInt32();
        }
        public int Server_FSMSaveDeviceConfiguration(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, byte[] p1, int p2, string p3, string p4, byte[] p5, int p6)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.Write_7(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"), p2);
            m.WriteInt32(p2);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p3, "p3"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p4, "p4"));
            m.Write_8(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p5, "p5"), p6);
            m.WriteInt32(p6);
            _Unmarshal_Helper u = SendReceive(10, m);
            return u.ReadInt32();
        }
        public int Server_FSMDeleteDeviceConfiguration(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, byte[] p1, int p2, string p3, string p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.Write_7(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"), p2);
            m.WriteInt32(p2);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p3, "p3"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p4, "p4"));
            _Unmarshal_Helper u = SendReceive(11, m);
            return u.ReadInt32();
        }
        public int Server_FSMUpdateDeviceInterfaceProperty(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, string p1, byte[] p2, int p3, int p4, byte[] p5, int p6)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            m.Write_9(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"), p3);
            m.WriteInt32(p3);
            m.WriteInt32(p4);
            m.Write_8(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p5, "p5"), p6);
            m.WriteInt32(p6);
            _Unmarshal_Helper u = SendReceive(12, m);
            return u.ReadInt32();
        }
        public int Server_FSMUpdateDeviceInterfaceRegistry(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, string p1, string p2, int p3, byte[] p4, int p5)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"));
            m.WriteInt32(p3);
            m.Write_10(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p4, "p4"), p5);
            m.WriteInt32(p5);
            _Unmarshal_Helper u = SendReceive(13, m);
            return u.ReadInt32();
        }
        public int Server_FSMUpdateDeviceState(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, int p1, string p2, out int p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt32(p1);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"));
            _Unmarshal_Helper u = SendReceive(14, m);
            p3 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int Server_FSMCloseClientSession(ref NtApiDotNet.Ndr.Marshal.NdrContextHandle p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(15, m);
            p0 = u.ReadContextHandle();
            return u.ReadInt32();
        }
        public int AllocateSystemBuffers(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, int p1, int p2, ref long[] p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt32(p1);
            m.WriteInt32(p2);
            m.WriteReferent(p3, new System.Action<long[], long>(m.Write_11), p1);
            _Unmarshal_Helper u = SendReceive(16, m);
            p3 = u.ReadReferent<long[]>(new System.Func<long[]>(u.Read_11), false);
            return u.ReadInt32();
        }
        public int AllocateSystemBuffers_17(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, int p1, long[] p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt32(p1);
            m.WriteReferent(p2, new System.Action<long[], long>(m.Write_12), p1);
            _Unmarshal_Helper u = SendReceive(17, m);
            return u.ReadInt32();
        }
        public int Server_FSMCreateVirtualCamera(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, NtApiDotNet.Ndr.Marshal.NdrEnum16 p1, NtApiDotNet.Ndr.Marshal.NdrEnum16 p2, NtApiDotNet.Ndr.Marshal.NdrEnum16 p3, string p4, string p5, System.Guid[] p6, int p7, byte[] p8, int p9, out long p10)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteEnum16(p1);
            m.WriteEnum16(p2);
            m.WriteEnum16(p3);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p4, "p4"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p5, "p5"));
            m.WriteReferent(p6, new System.Action<System.Guid[], long>(m.Write_13), p7);
            m.WriteInt32(p7);
            m.WriteReferent(p8, new System.Action<byte[], long>(m.Write_14), p9);
            m.WriteInt32(p9);
            _Unmarshal_Helper u = SendReceive(18, m);
            p10 = u.ReadInt64();
            return u.ReadInt32();
        }
        public int Server_FSMSetVirtualCameraState(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, long p1, NtApiDotNet.Ndr.Marshal.NdrEnum16 p2, byte[] p3, int p4, byte[] p5, int p6, byte[] p7, int p8, byte[] p9, int p10, byte[] p11, int p12, byte[] p13, int p14)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt64(p1);
            m.WriteEnum16(p2);
            m.WriteReferent(p3, new System.Action<byte[], long>(m.Write_15), p4);
            m.WriteInt32(p4);
            m.WriteReferent(p5, new System.Action<byte[], long>(m.Write_16), p6);
            m.WriteInt32(p6);
            m.WriteReferent(p7, new System.Action<byte[], long>(m.Write_17), p8);
            m.WriteInt32(p8);
            m.WriteReferent(p9, new System.Action<byte[], long>(m.Write_18), p10);
            m.WriteInt32(p10);
            m.WriteReferent(p11, new System.Action<byte[], long>(m.Write_19), p12);
            m.WriteInt32(p12);
            m.WriteReferent(p13, new System.Action<byte[], long>(m.Write_20), p14);
            m.WriteInt32(p14);
            _Unmarshal_Helper u = SendReceive(19, m);
            return u.ReadInt32();
        }
        public int Server_FSMGetVirtualCameraAttributes(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, long p1, ref byte[] p2, int p3, out int p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt64(p1);
            m.WriteReferent(p2, new System.Action<byte[], long>(m.Write_21), p3);
            m.WriteInt32(p3);
            _Unmarshal_Helper u = SendReceive(20, m);
            p2 = u.ReadReferent<byte[]>(new System.Func<byte[]>(u.Read_21), false);
            p4 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int Server_FSMPublishSensorGroups(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, long p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt64(p1);
            _Unmarshal_Helper u = SendReceive(21, m);
            return u.ReadInt32();
        }
        public int Server_FSMSendData(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, byte[] p1, int p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteReferent(p1, new System.Action<byte[], long>(m.Write_7), p2);
            m.WriteInt32(p2);
            _Unmarshal_Helper u = SendReceive(22, m);
            return u.ReadInt32();
        }
        public int Server_FSMGetSessionData(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, NtApiDotNet.Ndr.Marshal.NdrEnum16 p1, ref byte[] p2, int p3, out int p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteEnum16(p1);
            m.WriteReferent(p2, new System.Action<byte[], long>(m.Write_22), p3);
            m.WriteInt32(p3);
            _Unmarshal_Helper u = SendReceive(23, m);
            p2 = u.ReadReferent<byte[]>(new System.Func<byte[]>(u.Read_22), false);
            p4 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int Server_GenerateKernelDump(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, int p1, int p2, string p3, string p4, out int p5)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt32(p1);
            m.WriteInt32(p2);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p3, "p3"));
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p4, "p4"));
            _Unmarshal_Helper u = SendReceive(24, m);
            p5 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int Server_FSMSetSessionCommand(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, NtApiDotNet.Ndr.Marshal.NdrEnum16 p1, byte[] p2, int p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteEnum16(p1);
            m.WriteReferent(p2, new System.Action<byte[], long>(m.Write_9), p3);
            m.WriteInt32(p3);
            _Unmarshal_Helper u = SendReceive(25, m);
            return u.ReadInt32();
        }
    }
    #endregion
}

