//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Source Executable: c:\windows\system32\apxsvc.dll
// Interface ID: c574536e-f3f3-4c12-aebe-1adc93aa8e78
// Interface Version: 1.0
// Client Generated: 3/4/2026 7:36:49 PM
// NtApiDotNet Version: 1.1.33

namespace rpc_c574536e_f3f3_4c12_aebe_1adc93aa8e78_1_0
{
    
    #region Marshal Helpers
    internal class _Marshal_Helper : NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer
    {
        public void Write_0(Struct_0 p0)
        {
            WriteStruct<Struct_0>(p0);
        }
    }
    internal class _Unmarshal_Helper : NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer
    {
        public _Unmarshal_Helper(NtApiDotNet.Win32.Rpc.RpcClientResponse r) : 
                base(r.NdrBuffer, r.Handles, r.DataRepresentation)
        {
        }
        public _Unmarshal_Helper(byte[] ba) : 
                base(ba)
        {
        }
        public Struct_0 Read_0()
        {
            return ReadStruct<Struct_0>();
        }
    }
    #endregion
    #region Complex Types
    public struct Struct_0 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteInt32(Member4);
            m.WriteGuid(Member8);
            m.WriteGuid(Member18);
            m.WriteGuid(Member28);
            m.WriteInt16(Member38);
            m.WriteInt16(Member3A);
            m.WriteInt32(Member3C);
            m.WriteInt16(Member40);
            m.WriteEmbeddedPointer<string>(Member48, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member50, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member58, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member60, new System.Action<string>(m.WriteTerminatedString));
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member4 = u.ReadInt32();
            Member8 = u.ReadGuid();
            Member18 = u.ReadGuid();
            Member28 = u.ReadGuid();
            Member38 = u.ReadInt16();
            Member3A = u.ReadInt16();
            Member3C = u.ReadInt32();
            Member40 = u.ReadInt16();
            Member48 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member50 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member58 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member60 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public int Member4;
        public System.Guid Member8;
        public System.Guid Member18;
        public System.Guid Member28;
        public short Member38;
        public short Member3A;
        public int Member3C;
        public short Member40;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member48;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member50;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member58;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member60;
        public static Struct_0 CreateDefault()
        {
            return new Struct_0();
        }
        public Struct_0(int Member0, int Member4, System.Guid Member8, System.Guid Member18, System.Guid Member28, short Member38, short Member3A, int Member3C, short Member40, string Member48, string Member50, string Member58, string Member60)
        {
            this.Member0 = Member0;
            this.Member4 = Member4;
            this.Member8 = Member8;
            this.Member18 = Member18;
            this.Member28 = Member28;
            this.Member38 = Member38;
            this.Member3A = Member3A;
            this.Member3C = Member3C;
            this.Member40 = Member40;
            this.Member48 = Member48;
            this.Member50 = Member50;
            this.Member58 = Member58;
            this.Member60 = Member60;
        }
    }
    #endregion
    #region Client Implementation
    public sealed class Client : NtApiDotNet.Win32.Rpc.RpcClientBase
    {
        public Client() : 
                base("c574536e-f3f3-4c12-aebe-1adc93aa8e78", 1, 0)
        {
        }
        private _Unmarshal_Helper SendReceive(int p, _Marshal_Helper m)
        {
            return new _Unmarshal_Helper(SendReceive(p, m.DataRepresentation, m.ToArray(), m.Handles));
        }
        public int s_ApfDeviceCreateRpc(Struct_0 p0, out NtApiDotNet.Ndr.Marshal.NdrContextHandle p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.Write_0(p0);
            _Unmarshal_Helper u = SendReceive(0, m);
            p1 = u.ReadContextHandle();
            return u.ReadInt32();
        }
        public int s_ApfDeviceRemoveRpc(ref NtApiDotNet.Ndr.Marshal.NdrContextHandle p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(1, m);
            p0 = u.ReadContextHandle();
            return u.ReadInt32();
        }
    }
    #endregion
}

