//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Source Executable: c:\windows\system32\ime\imejp\imjpdct.exe
// Interface ID: cb407bbf-c14f-4cd9-8f55-cbb08146598c
// Interface Version: 0.0
// Client Generated: 3/4/2026 7:36:20 PM
// NtApiDotNet Version: 1.1.33

namespace rpc_cb407bbf_c14f_4cd9_8f55_cbb08146598c_0_0
{
    
    #region Marshal Helpers
    internal class _Marshal_Helper : NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer
    {
        public void Write_0(Struct_0 p0)
        {
            WriteStruct<Struct_0>(p0);
        }
        public void Write_1(string p0)
        {
            WriteFixedString(p0, 64);
        }
        public void Write_2(string p0)
        {
            WriteFixedString(p0, 260);
        }
    }
    internal class _Unmarshal_Helper : NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer
    {
        public _Unmarshal_Helper(NtApiDotNet.Win32.Rpc.RpcClientResponse r) : 
                base(r.NdrBuffer, r.Handles, r.DataRepresentation)
        {
        }
        public _Unmarshal_Helper(byte[] ba) : 
                base(ba)
        {
        }
        public Struct_0 Read_0()
        {
            return ReadStruct<Struct_0>();
        }
        public string Read_1()
        {
            return ReadFixedString(64);
        }
        public string Read_2()
        {
            return ReadFixedString(260);
        }
    }
    #endregion
    #region Complex Types
    public struct Struct_0 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteInt32(Member4);
            m.WriteInt64(Member8);
            m.WriteInt32(Member10);
            m.WriteInt32(Member14);
            m.WriteInt32(Member18);
            m.WriteInt16(Member1C);
            m.Write_1(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(Member1E, "Member1E"));
            m.Write_1(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(Member9E, "Member9E"));
            m.Write_2(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(Member11E, "Member11E"));
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member4 = u.ReadInt32();
            Member8 = u.ReadInt64();
            Member10 = u.ReadInt32();
            Member14 = u.ReadInt32();
            Member18 = u.ReadInt32();
            Member1C = u.ReadInt16();
            Member1E = u.Read_1();
            Member9E = u.Read_1();
            Member11E = u.Read_2();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public int Member0;
        public int Member4;
        public long Member8;
        public int Member10;
        public int Member14;
        public int Member18;
        public short Member1C;
        public string Member1E;
        public string Member9E;
        public string Member11E;
        public static Struct_0 CreateDefault()
        {
            Struct_0 ret = new Struct_0();
            ret.Member1E = new string('\0', 64);
            ret.Member9E = new string('\0', 64);
            ret.Member11E = new string('\0', 260);
            return ret;
        }
        public Struct_0(int Member0, int Member4, long Member8, int Member10, int Member14, int Member18, short Member1C, string Member1E, string Member9E, string Member11E)
        {
            this.Member0 = Member0;
            this.Member4 = Member4;
            this.Member8 = Member8;
            this.Member10 = Member10;
            this.Member14 = Member14;
            this.Member18 = Member18;
            this.Member1C = Member1C;
            this.Member1E = Member1E;
            this.Member9E = Member9E;
            this.Member11E = Member11E;
        }
    }
    #endregion
    #region Client Implementation
    public sealed class Client : NtApiDotNet.Win32.Rpc.RpcClientBase
    {
        public Client() : 
                base("cb407bbf-c14f-4cd9-8f55-cbb08146598c", 0, 0)
        {
        }
        private _Unmarshal_Helper SendReceive(int p, _Marshal_Helper m)
        {
            return new _Unmarshal_Helper(SendReceive(p, m.DataRepresentation, m.ToArray(), m.Handles));
        }
        public void Rpc_Open(Struct_0 p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.Write_0(p0);
            _Unmarshal_Helper u = SendReceive(0, m);
        }
        public void Rpc_GetServerProcessId(out int p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(1, m);
            p0 = u.ReadInt32();
        }
    }
    #endregion
}

