//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Source Executable: c:\windows\system32\zthelper.dll
// Interface ID: e9ca88c8-7d03-46cb-94d0-933a9a45908b
// Interface Version: 1.0
// Client Generated: 3/4/2026 7:38:59 PM
// NtApiDotNet Version: 1.1.33

namespace rpc_e9ca88c8_7d03_46cb_94d0_933a9a45908b_1_0
{
    
    #region Marshal Helpers
    internal class _Marshal_Helper : NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer
    {
        public void Write_0(Struct_0 p0)
        {
            WriteStruct<Struct_0>(p0);
        }
        public void Write_1(Struct_1 p0)
        {
            WriteStruct<Struct_1>(p0);
        }
        public void Write_2(Struct_2 p0)
        {
            WriteStruct<Struct_2>(p0);
        }
        public void Write_3(Struct_3 p0)
        {
            WriteStruct<Struct_3>(p0);
        }
        public void Write_4(Union_4 p0, long p1)
        {
            WriteUnion<Union_4>(p0, p1);
        }
        public void Write_5(Struct_5 p0)
        {
            WriteStruct<Struct_5>(p0);
        }
        public void Write_6(Struct_6 p0)
        {
            WriteStruct<Struct_6>(p0);
        }
        public void Write_7(Struct_7 p0)
        {
            WriteStruct<Struct_7>(p0);
        }
        public void Write_8(Struct_8 p0)
        {
            WriteStruct<Struct_8>(p0);
        }
        public void Write_9(Struct_9 p0)
        {
            WriteStruct<Struct_9>(p0);
        }
        public void Write_10(Struct_10 p0)
        {
            WriteStruct<Struct_10>(p0);
        }
        public void Write_11(Struct_11 p0)
        {
            WriteStruct<Struct_11>(p0);
        }
        public void Write_12(Struct_2[] p0, long p1)
        {
            WriteConformantStructArray<Struct_2>(p0, p1);
        }
        public void Write_13(Struct_5[] p0, long p1)
        {
            WriteConformantStructArray<Struct_5>(p0, p1);
        }
        public void Write_14(int[] p0)
        {
            WriteFixedPrimitiveArray<int>(p0, 7);
        }
        public void Write_15(Struct_6[] p0, long p1)
        {
            WriteConformantStructArray<Struct_6>(p0, p1);
        }
        public void Write_16(Struct_8[] p0, long p1)
        {
            WriteConformantStructArray<Struct_8>(p0, p1);
        }
        public void Write_17(string[] p0, long p1)
        {
            WriteConformantStringArray(p0, new System.Action<string>(this.WriteTerminatedString), p1);
        }
        public void Write_18(sbyte[] p0)
        {
            WriteFixedPrimitiveArray<sbyte>(p0, 32);
        }
    }
    internal class _Unmarshal_Helper : NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer
    {
        public _Unmarshal_Helper(NtApiDotNet.Win32.Rpc.RpcClientResponse r) : 
                base(r.NdrBuffer, r.Handles, r.DataRepresentation)
        {
        }
        public _Unmarshal_Helper(byte[] ba) : 
                base(ba)
        {
        }
        public Struct_0 Read_0()
        {
            return ReadStruct<Struct_0>();
        }
        public Struct_1 Read_1()
        {
            return ReadStruct<Struct_1>();
        }
        public Struct_2 Read_2()
        {
            return ReadStruct<Struct_2>();
        }
        public Struct_3 Read_3()
        {
            return ReadStruct<Struct_3>();
        }
        public Union_4 Read_4()
        {
            return ReadStruct<Union_4>();
        }
        public Struct_5 Read_5()
        {
            return ReadStruct<Struct_5>();
        }
        public Struct_6 Read_6()
        {
            return ReadStruct<Struct_6>();
        }
        public Struct_7 Read_7()
        {
            return ReadStruct<Struct_7>();
        }
        public Struct_8 Read_8()
        {
            return ReadStruct<Struct_8>();
        }
        public Struct_9 Read_9()
        {
            return ReadStruct<Struct_9>();
        }
        public Struct_10 Read_10()
        {
            return ReadStruct<Struct_10>();
        }
        public Struct_11 Read_11()
        {
            return ReadStruct<Struct_11>();
        }
        public Struct_2[] Read_12()
        {
            return ReadConformantStructArray<Struct_2>();
        }
        public Struct_5[] Read_13()
        {
            return ReadConformantStructArray<Struct_5>();
        }
        public int[] Read_14()
        {
            return ReadFixedPrimitiveArray<int>(7);
        }
        public Struct_6[] Read_15()
        {
            return ReadConformantStructArray<Struct_6>();
        }
        public Struct_8[] Read_16()
        {
            return ReadConformantStructArray<Struct_8>();
        }
        public string[] Read_17()
        {
            return ReadConformantStringArray(new System.Func<string>(this.ReadConformantVaryingString));
        }
        public sbyte[] Read_18()
        {
            return ReadFixedPrimitiveArray<sbyte>(32);
        }
    }
    #endregion
    #region Complex Types
    public struct Struct_0 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteInt64(Member8);
            m.WriteEmbeddedPointer<Struct_1>(Member10, new System.Action<Struct_1>(m.Write_1));
            m.WriteEmbeddedPointer<Struct_2[], long>(Member18, new System.Action<Struct_2[], long>(m.Write_12), Member20);
            m.WriteInt32(Member20);
            m.WriteEmbeddedPointer<Struct_5[], long>(Member28, new System.Action<Struct_5[], long>(m.Write_13), Member30);
            m.WriteInt32(Member30);
            m.WriteEmbeddedPointer<Struct_7>(Member38, new System.Action<Struct_7>(m.Write_7));
            m.WriteEmbeddedPointer<Struct_9>(Member40, new System.Action<Struct_9>(m.Write_9));
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadInt64();
            Member10 = u.ReadEmbeddedPointer<Struct_1>(new System.Func<Struct_1>(u.Read_1), false);
            Member18 = u.ReadEmbeddedPointer<Struct_2[]>(new System.Func<Struct_2[]>(u.Read_12), false);
            Member20 = u.ReadInt32();
            Member28 = u.ReadEmbeddedPointer<Struct_5[]>(new System.Func<Struct_5[]>(u.Read_13), false);
            Member30 = u.ReadInt32();
            Member38 = u.ReadEmbeddedPointer<Struct_7>(new System.Func<Struct_7>(u.Read_7), false);
            Member40 = u.ReadEmbeddedPointer<Struct_9>(new System.Func<Struct_9>(u.Read_9), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public int Member0;
        public long Member8;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_1> Member10;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_2[]> Member18;
        public int Member20;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_5[]> Member28;
        public int Member30;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_7> Member38;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_9> Member40;
        public static Struct_0 CreateDefault()
        {
            return new Struct_0();
        }
        public Struct_0(int Member0, long Member8, System.Nullable<Struct_1> Member10, Struct_2[] Member18, int Member20, Struct_5[] Member28, int Member30, System.Nullable<Struct_7> Member38, System.Nullable<Struct_9> Member40)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member10 = Member10;
            this.Member18 = Member18;
            this.Member20 = Member20;
            this.Member28 = Member28;
            this.Member30 = Member30;
            this.Member38 = Member38;
            this.Member40 = Member40;
        }
    }
    public struct Struct_1 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteInt64(Member8);
            m.WriteEnum16(Member10);
            m.WriteInt32(Member14);
            m.WriteInt32(Member18);
            m.WriteInt32(Member1C);
            m.WriteInt32(Member20);
            m.WriteInt32(Member24);
            m.WriteInt32(Member28);
            m.WriteInt32(Member2C);
            m.WriteInt32(Member30);
            m.WriteEnum16(Member34);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadInt64();
            Member10 = u.ReadEnum16();
            Member14 = u.ReadInt32();
            Member18 = u.ReadInt32();
            Member1C = u.ReadInt32();
            Member20 = u.ReadInt32();
            Member24 = u.ReadInt32();
            Member28 = u.ReadInt32();
            Member2C = u.ReadInt32();
            Member30 = u.ReadInt32();
            Member34 = u.ReadEnum16();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public int Member0;
        public long Member8;
        public NtApiDotNet.Ndr.Marshal.NdrEnum16 Member10;
        public int Member14;
        public int Member18;
        public int Member1C;
        public int Member20;
        public int Member24;
        public int Member28;
        public int Member2C;
        public int Member30;
        public NtApiDotNet.Ndr.Marshal.NdrEnum16 Member34;
        public static Struct_1 CreateDefault()
        {
            return new Struct_1();
        }
        public Struct_1(int Member0, long Member8, NtApiDotNet.Ndr.Marshal.NdrEnum16 Member10, int Member14, int Member18, int Member1C, int Member20, int Member24, int Member28, int Member2C, int Member30, NtApiDotNet.Ndr.Marshal.NdrEnum16 Member34)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member10 = Member10;
            this.Member14 = Member14;
            this.Member18 = Member18;
            this.Member1C = Member1C;
            this.Member20 = Member20;
            this.Member24 = Member24;
            this.Member28 = Member28;
            this.Member2C = Member2C;
            this.Member30 = Member30;
            this.Member34 = Member34;
        }
    }
    public struct Struct_2 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteInt64(Member8);
            m.Write_3(Member10);
            m.WriteInt16(Member2C);
            m.WriteInt16(Member2E);
            m.WriteEnum16(Member30);
            m.Write_4(Member38, Member30);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadInt64();
            Member10 = u.Read_3();
            Member2C = u.ReadInt16();
            Member2E = u.ReadInt16();
            Member30 = u.ReadEnum16();
            Member38 = u.Read_4();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public int Member0;
        public long Member8;
        public Struct_3 Member10;
        public short Member2C;
        public short Member2E;
        public NtApiDotNet.Ndr.Marshal.NdrEnum16 Member30;
        public Union_4 Member38;
        public static Struct_2 CreateDefault()
        {
            return new Struct_2();
        }
        public Struct_2(int Member0, long Member8, Struct_3 Member10, short Member2C, short Member2E, NtApiDotNet.Ndr.Marshal.NdrEnum16 Member30, Union_4 Member38)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member10 = Member10;
            this.Member2C = Member2C;
            this.Member2E = Member2E;
            this.Member30 = Member30;
            this.Member38 = Member38;
        }
    }
    public struct Struct_3 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.Write_14(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(Member0, "Member0"));
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.Read_14();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int[] Member0;
        public static Struct_3 CreateDefault()
        {
            Struct_3 ret = new Struct_3();
            ret.Member0 = new int[7];
            return ret;
        }
        public Struct_3(int[] Member0)
        {
            this.Member0 = Member0;
        }
    }
    public struct Union_4 : NtApiDotNet.Ndr.Marshal.INdrNonEncapsulatedUnion
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            throw new System.NotImplementedException();
        }
        void NtApiDotNet.Ndr.Marshal.INdrNonEncapsulatedUnion.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m, long l)
        {
            Selector = ((NtApiDotNet.Ndr.Marshal.NdrEnum16)(l));
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteEnum16(Selector);
            if ((Selector == 1))
            {
                m.WriteEmbeddedPointer<string>(Arm_1, new System.Action<string>(m.WriteTerminatedString));
                goto done;
            }
            if ((Selector == 2))
            {
                m.WriteEmbeddedPointer<string>(Arm_2, new System.Action<string>(m.WriteTerminatedString));
                goto done;
            }
            if ((Selector == 0))
            {
                m.WriteEmpty(Arm_0);
                goto done;
            }
            throw new System.ArgumentException("No matching union selector when marshaling Union_4");
        done:
            return;
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Selector = u.ReadEnum16();
            if ((Selector == 1))
            {
                Arm_1 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
                goto done;
            }
            if ((Selector == 2))
            {
                Arm_2 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
                goto done;
            }
            if ((Selector == 0))
            {
                Arm_0 = u.ReadEmpty();
                goto done;
            }
            throw new System.ArgumentException("No matching union selector when marshaling Union_4");
        done:
            return;
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 1;
        }
        private NtApiDotNet.Ndr.Marshal.NdrEnum16 Selector;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Arm_1;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Arm_2;
        public NtApiDotNet.Ndr.Marshal.NdrEmpty Arm_0;
        public static Union_4 CreateDefault()
        {
            return new Union_4();
        }
        public Union_4(NtApiDotNet.Ndr.Marshal.NdrEnum16 Selector, string Arm_1, string Arm_2, NtApiDotNet.Ndr.Marshal.NdrEmpty Arm_0)
        {
            this.Selector = Selector;
            this.Arm_1 = Arm_1;
            this.Arm_2 = Arm_2;
            this.Arm_0 = Arm_0;
        }
    }
    public struct Struct_5 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteInt64(Member8);
            m.WriteEmbeddedPointer<string>(Member10, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member18, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<Struct_6[], long>(Member20, new System.Action<Struct_6[], long>(m.Write_15), Member28);
            m.WriteInt32(Member28);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadInt64();
            Member10 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member18 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member20 = u.ReadEmbeddedPointer<Struct_6[]>(new System.Func<Struct_6[]>(u.Read_15), false);
            Member28 = u.ReadInt32();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public int Member0;
        public long Member8;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member10;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member18;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_6[]> Member20;
        public int Member28;
        public static Struct_5 CreateDefault()
        {
            return new Struct_5();
        }
        public Struct_5(int Member0, long Member8, string Member10, string Member18, Struct_6[] Member20, int Member28)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member10 = Member10;
            this.Member18 = Member18;
            this.Member20 = Member20;
            this.Member28 = Member28;
        }
    }
    public struct Struct_6 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.Write_3(Member0);
            m.WriteSByte(Member1C);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.Read_3();
            Member1C = u.ReadSByte();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public Struct_3 Member0;
        public sbyte Member1C;
        public static Struct_6 CreateDefault()
        {
            return new Struct_6();
        }
        public Struct_6(Struct_3 Member0, sbyte Member1C)
        {
            this.Member0 = Member0;
            this.Member1C = Member1C;
        }
    }
    public struct Struct_7 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteInt64(Member8);
            m.WriteEmbeddedPointer<Struct_8[], long>(Member10, new System.Action<Struct_8[], long>(m.Write_16), Member18);
            m.WriteInt32(Member18);
            m.WriteEmbeddedPointer<string[], long>(Member20, new System.Action<string[], long>(m.Write_17), Member28);
            m.WriteInt32(Member28);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadInt64();
            Member10 = u.ReadEmbeddedPointer<Struct_8[]>(new System.Func<Struct_8[]>(u.Read_16), false);
            Member18 = u.ReadInt32();
            Member20 = u.ReadEmbeddedPointer<string[]>(new System.Func<string[]>(u.Read_17), false);
            Member28 = u.ReadInt32();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public int Member0;
        public long Member8;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_8[]> Member10;
        public int Member18;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string[]> Member20;
        public int Member28;
        public static Struct_7 CreateDefault()
        {
            return new Struct_7();
        }
        public Struct_7(int Member0, long Member8, Struct_8[] Member10, int Member18, string[] Member20, int Member28)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member10 = Member10;
            this.Member18 = Member18;
            this.Member20 = Member20;
            this.Member28 = Member28;
        }
    }
    public struct Struct_8 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.Write_18(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(Member0, "Member0"));
            m.WriteInt32(Member20);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.Read_18();
            Member20 = u.ReadInt32();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public sbyte[] Member0;
        public int Member20;
        public static Struct_8 CreateDefault()
        {
            Struct_8 ret = new Struct_8();
            ret.Member0 = new sbyte[32];
            return ret;
        }
        public Struct_8(sbyte[] Member0, int Member20)
        {
            this.Member0 = Member0;
            this.Member20 = Member20;
        }
    }
    public struct Struct_9 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteInt64(Member8);
            m.WriteEmbeddedPointer<Struct_8[], long>(Member10, new System.Action<Struct_8[], long>(m.Write_16), Member18);
            m.WriteInt32(Member18);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadInt64();
            Member10 = u.ReadEmbeddedPointer<Struct_8[]>(new System.Func<Struct_8[]>(u.Read_16), false);
            Member18 = u.ReadInt32();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public int Member0;
        public long Member8;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_8[]> Member10;
        public int Member18;
        public static Struct_9 CreateDefault()
        {
            return new Struct_9();
        }
        public Struct_9(int Member0, long Member8, Struct_8[] Member10, int Member18)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member10 = Member10;
            this.Member18 = Member18;
        }
    }
    public struct Struct_10 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.Write_11(Member4);
            m.WriteGuid(Member8);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member4 = u.Read_11();
            Member8 = u.ReadGuid();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public Struct_11 Member4;
        public System.Guid Member8;
        public static Struct_10 CreateDefault()
        {
            return new Struct_10();
        }
        public Struct_10(int Member0, Struct_11 Member4, System.Guid Member8)
        {
            this.Member0 = Member0;
            this.Member4 = Member4;
            this.Member8 = Member8;
        }
    }
    public struct Struct_11 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public static Struct_11 CreateDefault()
        {
            return new Struct_11();
        }
        public Struct_11(int Member0)
        {
            this.Member0 = Member0;
        }
    }
    #endregion
    #region Client Implementation
    public sealed class Client : NtApiDotNet.Win32.Rpc.RpcClientBase
    {
        public Client() : 
                base("e9ca88c8-7d03-46cb-94d0-933a9a45908b", 1, 0)
        {
        }
        private _Unmarshal_Helper SendReceive(int p, _Marshal_Helper m)
        {
            return new _Unmarshal_Helper(SendReceive(p, m.DataRepresentation, m.ToArray(), m.Handles));
        }
        public int R_ZtHelperSetZtSettings(System.Nullable<Struct_0> p0, long p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteReferent(p0, new System.Action<Struct_0>(m.Write_0));
            m.WriteInt64(p1);
            _Unmarshal_Helper u = SendReceive(0, m);
            return u.ReadInt32();
        }
        public int R_ZtHelperGetZtSettings(long p0, NtApiDotNet.Ndr.Marshal.NdrEnum16 p1, out System.Nullable<Struct_0> p2, out Struct_10 p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteInt64(p0);
            m.WriteEnum16(p1);
            _Unmarshal_Helper u = SendReceive(1, m);
            p2 = u.ReadReferentValue<Struct_0>(new System.Func<Struct_0>(u.Read_0), false);
            p3 = u.Read_10();
            return u.ReadInt32();
        }
        public int R_ZtHelperGrantAccessToClientCerts(NtApiDotNet.Ndr.Marshal.NdrEnum16 p0, Struct_10 p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteEnum16(p0);
            m.Write_10(p1);
            _Unmarshal_Helper u = SendReceive(2, m);
            return u.ReadInt32();
        }
        public int R_ZtHelperPromoteConfig(Struct_10 p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.Write_10(p0);
            _Unmarshal_Helper u = SendReceive(3, m);
            return u.ReadInt32();
        }
    }
    #endregion
}

