//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Source Executable: c:\windows\system32\sudo.exe
// Interface ID: f691b703-f681-47dc-afcd-034b2faab911
// Interface Version: 1.0
// Client Generated: 3/4/2026 7:38:28 PM
// NtApiDotNet Version: 1.1.33

namespace rpc_f691b703_f681_47dc_afcd_034b2faab911_1_0
{
    
    #region Marshal Helpers
    internal class _Marshal_Helper : NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer
    {
        public void Write_0(Struct_0 p0)
        {
            WriteStruct<Struct_0>(p0);
        }
        public void Write_1(sbyte[] p0, long p1)
        {
            WriteConformantArray<sbyte>(p0, p1);
        }
        public void Write_2(NtApiDotNet.NtProcess p0)
        {
            WriteSystemHandle<NtApiDotNet.NtProcess>(p0);
        }
        public void Write_3(NtApiDotNet.NtFile p0)
        {
            WriteSystemHandle<NtApiDotNet.NtFile>(p0);
        }
        public void Write_4(NtApiDotNet.NtFile[] p0, long p1)
        {
            WriteConformantArrayCallback<NtApiDotNet.NtFile>(p0, new System.Action<NtApiDotNet.NtFile>(this.Write_3), p1);
        }
        public void Write_5(NtApiDotNet.NtFile p0)
        {
            WriteSystemHandle<NtApiDotNet.NtFile>(p0);
        }
        public void Write_6(NtApiDotNet.NtFile[] p0, long p1)
        {
            WriteConformantArrayCallback<NtApiDotNet.NtFile>(p0, new System.Action<NtApiDotNet.NtFile>(this.Write_5), p1);
        }
    }
    internal class _Unmarshal_Helper : NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer
    {
        public _Unmarshal_Helper(NtApiDotNet.Win32.Rpc.RpcClientResponse r) : 
                base(r.NdrBuffer, r.Handles, r.DataRepresentation)
        {
        }
        public _Unmarshal_Helper(byte[] ba) : 
                base(ba)
        {
        }
        public Struct_0 Read_0()
        {
            return ReadStruct<Struct_0>();
        }
        public sbyte[] Read_1()
        {
            return ReadConformantArray<sbyte>();
        }
        public NtApiDotNet.NtProcess Read_2()
        {
            return ReadSystemHandle<NtApiDotNet.NtProcess>();
        }
        public NtApiDotNet.NtFile Read_3()
        {
            return ReadSystemHandle<NtApiDotNet.NtFile>();
        }
        public NtApiDotNet.NtFile[] Read_4()
        {
            return ReadConformantArrayCallback<NtApiDotNet.NtFile>(new System.Func<NtApiDotNet.NtFile>(this.Read_3));
        }
        public NtApiDotNet.NtFile Read_5()
        {
            return ReadSystemHandle<NtApiDotNet.NtFile>();
        }
        public NtApiDotNet.NtFile[] Read_6()
        {
            return ReadConformantArrayCallback<NtApiDotNet.NtFile>(new System.Func<NtApiDotNet.NtFile>(this.Read_5));
        }
    }
    #endregion
    #region Complex Types
    public struct Struct_0 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteEmbeddedPointer<sbyte[], long>(Member8, new System.Action<sbyte[], long>(m.Write_1), Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<sbyte[]>(new System.Func<sbyte[]>(u.Read_1), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<sbyte[]> Member8;
        public static Struct_0 CreateDefault()
        {
            return new Struct_0();
        }
        public Struct_0(int Member0, sbyte[] Member8)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
        }
    }
    #endregion
    #region Client Implementation
    public sealed class Client : NtApiDotNet.Win32.Rpc.RpcClientBase
    {
        public Client() : 
                base("f691b703-f681-47dc-afcd-034b2faab911", 1, 0)
        {
        }
        private _Unmarshal_Helper SendReceive(int p, _Marshal_Helper m)
        {
            return new _Unmarshal_Helper(SendReceive(p, m.DataRepresentation, m.ToArray(), m.Handles));
        }
        public int server_DoElevationRequest(NtApiDotNet.NtProcess p0, NtApiDotNet.NtFile[] p1, NtApiDotNet.NtFile[] p2, int p3, Struct_0 p4, Struct_0 p5, Struct_0 p6, Struct_0 p7, System.Guid p8, out NtApiDotNet.NtProcess p9)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.Write_2(p0);
            m.WriteReferent(p1, new System.Action<NtApiDotNet.NtFile[], long>(m.Write_4), 3);
            m.WriteReferent(p2, new System.Action<NtApiDotNet.NtFile[], long>(m.Write_6), 3);
            m.WriteInt32(p3);
            m.Write_0(p4);
            m.Write_0(p5);
            m.Write_0(p6);
            m.Write_0(p7);
            m.WriteGuid(p8);
            _Unmarshal_Helper u = SendReceive(0, m);
            p9 = u.Read_2();
            return u.ReadInt32();
        }
        public void server_Shutdown()
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(1, m);
        }
    }
    #endregion
}

