#!/usr/bin/env python3
"""Generate IDL-like interface descriptions from reconstructed COM metadata.

Usage:
    python generate_idl.py <db_path>
    python generate_idl.py <db_path> --output interfaces.idl
    python generate_idl.py <db_path> --interface IAppInfoService
    python generate_idl.py <db_path> --json

Examples:
    python generate_idl.py extracted_dbs/appinfo_dll_e98d25a9e8.db
    python generate_idl.py extracted_dbs/appinfo_dll_e98d25a9e8.db --output reconstructed.idl
    python generate_idl.py extracted_dbs/appinfo_dll_e98d25a9e8.db --interface IAsyncOperation

Output:
    IDL-syntax interface blocks with method signatures, parameter types,
    HRESULT returns, and vtable slot comments.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any, Optional

from _common import (
    WORKSPACE_ROOT,
    IUNKNOWN_SLOTS,
    IINSPECTABLE_SLOTS,
    classify_vtable_as_com,
    decode_wrl_runtime_class,
    parse_com_class_from_mangled,
    parse_json_safe,
    parse_vtable_methods,
    resolve_db_path,
)

from helpers import open_individual_analysis_db
from helpers.errors import db_error_handler, safe_parse_args
from helpers.json_output import emit_json


def generate_idl(db_path: str, interface_filter: str = "") -> dict:
    """Generate IDL-like descriptions from COM metadata in a module.

    Returns dict with IDL text, parsed interface list, and summary.
    """
    with db_error_handler(db_path, "generating IDL"):
        with open_individual_analysis_db(db_path) as db:
            file_info = db.get_file_info()
            module_name = file_info.file_name if file_info else "(unknown)"
            all_functions = db.get_all_functions()

    # Collect all vtable skeletons (deduplicated)
    seen_skeletons: set[str] = set()
    interfaces: list[dict[str, Any]] = []

    for func in all_functions:
        vtable_ctx = parse_json_safe(func.vtable_contexts)
        if not vtable_ctx or not isinstance(vtable_ctx, list):
            continue

        for entry in vtable_ctx:
            if not isinstance(entry, dict):
                continue
            classes = entry.get("reconstructed_classes", [])
            source_ea = entry.get("source_ea", "")

            for skeleton in classes:
                if not isinstance(skeleton, str) or skeleton in seen_skeletons:
                    continue
                seen_skeletons.add(skeleton)

                methods = parse_vtable_methods(skeleton)
                if not methods:
                    continue

                # Extract class name first
                class_match = re.search(r'class\s+(?:[\w]+\s+)?([\w:]+(?:<[^>]+>)?)', skeleton)
                class_name = class_match.group(1) if class_match else "(unknown)"

                com_info = classify_vtable_as_com(methods, class_name=class_name)
                if not com_info["is_com"]:
                    continue

                # Apply filter
                if interface_filter and interface_filter.lower() not in class_name.lower():
                    continue

                interfaces.append({
                    "class_name": class_name,
                    "base_interface": com_info["base_interface"],
                    "custom_start_slot": com_info["custom_method_start_slot"],
                    "methods": methods,
                    "source_ea": source_ea,
                    "source_function_id": func.function_id,
                })

    # Also collect method signatures from function DB for richer IDL
    class_method_sigs: dict[str, list[dict]] = defaultdict(list)
    for func in all_functions:
        mangled = func.mangled_name or ""
        parsed = parse_com_class_from_mangled(mangled)
        if not parsed:
            continue
        cls = parsed["class_name"]
        if parsed["role"] == "method" and parsed["method_name"]:
            class_method_sigs[cls].append({
                "method_name": parsed["method_name"],
                "function_id": func.function_id,
                "signature": func.function_signature or "",
                "signature_extended": func.function_signature_extended or "",
            })

    # Generate IDL text
    idl_lines = _build_idl_text(module_name, interfaces, class_method_sigs)

    return {
        "module": module_name,
        "interface_count": len(interfaces),
        "interfaces": interfaces,
        "idl_text": "\n".join(idl_lines),
    }


def _build_idl_text(
    module_name: str,
    interfaces: list[dict],
    class_method_sigs: dict[str, list[dict]],
) -> list[str]:
    """Build IDL-like text from parsed interface data."""
    lines = [
        f"// Reconstructed COM Interfaces from: {module_name}",
        f"// Auto-generated by com-interface-reconstruction skill",
        f"// Slot offsets are x64 (8 bytes per slot)",
        "",
        'import "unknwn.idl";',
        "",
    ]

    for iface in interfaces:
        class_name = iface["class_name"]
        base = iface["base_interface"]
        custom_start = iface["custom_start_slot"]
        methods = iface["methods"]

        # Try to infer an interface name from the class name
        iface_name = _infer_interface_name(class_name)

        lines.append(f"// Source: vtable at {iface['source_ea']} (function #{iface['source_function_id']})")
        lines.append(f"// Class: {class_name}")
        lines.append(f"[uuid(unknown)]")
        lines.append(f"interface {iface_name} : {base}")
        lines.append("{")

        # Emit custom methods (skip base interface slots)
        custom_methods = [m for m in methods if m["slot"] >= custom_start]

        # Try to enrich with signatures from the function DB
        sig_lookup: dict[str, dict] = {}
        for sig_info in class_method_sigs.get(class_name, []):
            sig_lookup[sig_info["method_name"]] = sig_info

        for m in custom_methods:
            slot = m["slot"]
            offset = m["offset_hex"]
            method_name = m["method_name"]

            # Try to get a real signature
            sig_info = sig_lookup.get(method_name)
            if sig_info and sig_info["signature_extended"]:
                params = _extract_params_from_sig(sig_info["signature_extended"])
                ret_type = _extract_return_type(sig_info["signature_extended"])
                param_str = ", ".join(params) if params else ""
                lines.append(f"    // Slot {slot} ({offset})")
                lines.append(f"    {ret_type} {method_name}({param_str});")
            elif sig_info and sig_info["signature"]:
                params = _extract_params_from_sig(sig_info["signature"])
                ret_type = _extract_return_type(sig_info["signature"])
                param_str = ", ".join(params) if params else ""
                lines.append(f"    // Slot {slot} ({offset})")
                lines.append(f"    {ret_type} {method_name}({param_str});")
            else:
                lines.append(f"    // Slot {slot} ({offset})")
                lines.append(f"    HRESULT {method_name}(/* params unknown */);")

        lines.append("};")
        lines.append("")

    if not interfaces:
        lines.append("// No COM vtable interfaces detected in this module.")
        lines.append("")

    return lines


def _infer_interface_name(class_name: str) -> str:
    """Infer an interface name from a class name.

    Heuristics:
    - If class starts with 'C', generate 'I' prefix: CMyClass -> IMyClass
    - If class already starts with 'I', keep it
    - Otherwise prefix with 'I'
    """
    name = class_name.split("::")[-1]  # Use innermost name
    if name.startswith("C") and len(name) > 1 and name[1].isupper():
        return "I" + name[1:]
    if name.startswith("I") and len(name) > 1 and name[1].isupper():
        return name
    return "I" + name


def _extract_params_from_sig(signature: str) -> list[str]:
    """Extract parameter list from a function signature string."""
    # Find the parameter part between parentheses
    paren_match = re.search(r'\((.+)\)', signature)
    if not paren_match:
        return []

    params_str = paren_match.group(1).strip()
    if not params_str or params_str in ("void", ""):
        return []

    # Split by comma respecting template brackets
    depth = 0
    current = []
    params = []
    for ch in params_str:
        if ch in ('<', '('):
            depth += 1
            current.append(ch)
        elif ch in ('>', ')'):
            depth -= 1
            current.append(ch)
        elif ch == ',' and depth == 0:
            param = ''.join(current).strip()
            if param:
                params.append(_clean_param(param))
            current = []
        else:
            current.append(ch)
    remaining = ''.join(current).strip()
    if remaining:
        params.append(_clean_param(remaining))

    # Skip 'this' parameter (first param in __fastcall member functions)
    if params and ("this" in params[0].lower() or params[0].endswith("*") and "::" in signature):
        # The first param might be the implicit 'this'
        # Check if the function signature is a member function
        pass  # Keep all params -- IDA signatures typically don't include 'this' explicitly

    return params


def _clean_param(param: str) -> str:
    """Clean up an IDA parameter string for IDL output."""
    # Remove __fastcall, __stdcall, etc.
    param = re.sub(r'__\w+call\s*', '', param)
    # Remove leading/trailing whitespace
    return param.strip()


def _extract_return_type(signature: str) -> str:
    """Extract the return type from a function signature."""
    # Pattern: "return_type __calling_conv name(..."
    paren_idx = signature.find('(')
    if paren_idx < 0:
        return "HRESULT"
    prefix = signature[:paren_idx].strip()

    # Remove calling convention
    prefix = re.sub(r'__\w+call\s*', '', prefix)
    # Remove function name (last word)
    parts = prefix.rsplit(None, 1)
    if len(parts) >= 2:
        ret = parts[0].strip()
        # Map common IDA types to COM types
        if ret in ("__int64", "long long", "LONGLONG"):
            return "HRESULT"
        if ret == "__int32" or ret == "long":
            return "HRESULT"
        return ret
    return "HRESULT"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate IDL-like interface descriptions from COM metadata.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("db_path", help="Path to the individual analysis DB")
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    parser.add_argument("--output", dest="output_file",
                        help="Write IDL text to file instead of stdout")
    parser.add_argument("--interface", dest="interface_filter", default="",
                        help="Filter to interfaces matching this name pattern")
    args = safe_parse_args(parser)

    db_path = resolve_db_path(args.db_path)
    with db_error_handler(db_path, "IDL generation"):
        data = generate_idl(db_path, interface_filter=args.interface_filter)

    if args.json:
        emit_json(data)
    elif args.output_file:
        out_path = Path(args.output_file)
        out_path.write_text(data["idl_text"], encoding="utf-8")
        print(f"IDL written to {out_path} ({data['interface_count']} interfaces)")
    else:
        print(data["idl_text"])


if __name__ == "__main__":
    main()
