"""Tests for the RPC stub parser (helpers/rpc_stub_parser.py).

Covers:
  - RpcParameter risk scoring and serialisation
  - RpcProcedureSignature computed properties
  - Stub file parsing from synthetic and real .cs content
  - Directory-level stub loading
"""

from __future__ import annotations

import sys
import textwrap
from pathlib import Path

import pytest

_AGENT_DIR = Path(__file__).resolve().parent.parent
if str(_AGENT_DIR) not in sys.path:
    sys.path.insert(0, str(_AGENT_DIR))

from helpers.rpc_stub_parser import (
    RpcParameter,
    RpcProcedureSignature,
    RpcStubFile,
    load_stubs_from_directory,
    parse_stub_file,
)

_STUBS_DIR = _AGENT_DIR / "config" / "assets" / "rpc_data" / "rpc_clients_26200_7840"


# ===================================================================
# RpcParameter
# ===================================================================


class TestRpcParameter:
    """Unit tests for RpcParameter risk scoring and to_dict."""

    def test_risk_score_string(self):
        p = RpcParameter(name="p0", ndr_type="string", direction="in")
        assert p.risk_score == pytest.approx(0.8, abs=0.05)

    def test_risk_score_byte_array(self):
        p = RpcParameter(name="buf", ndr_type="byte[]", direction="in", is_array=True)
        assert p.risk_score == pytest.approx(0.9, abs=0.05)

    def test_risk_score_int(self):
        p = RpcParameter(name="flags", ndr_type="int", direction="in")
        assert p.risk_score == pytest.approx(0.3, abs=0.05)

    def test_risk_score_context_handle(self):
        p = RpcParameter(name="h", ndr_type="NdrContextHandle", direction="in")
        assert p.risk_score == pytest.approx(0.2, abs=0.05)

    def test_risk_score_struct(self):
        p = RpcParameter(name="s", ndr_type="Struct_0", direction="in")
        assert p.risk_score == pytest.approx(0.6, abs=0.05)

    def test_to_dict(self):
        p = RpcParameter(
            name="data",
            ndr_type="byte[]",
            direction="in",
            is_array=True,
            is_pointer=False,
        )
        d = p.to_dict()
        assert d["name"] == "data"
        assert d["ndr_type"] == "byte[]"
        assert d["direction"] == "in"
        assert d["is_array"] is True
        assert d["is_pointer"] is False
        assert "risk_score" in d


# ===================================================================
# RpcProcedureSignature
# ===================================================================


class TestRpcProcedureSignature:
    """Unit tests for RpcProcedureSignature computed properties."""

    @staticmethod
    def _make_sig(params: list[RpcParameter]) -> RpcProcedureSignature:
        return RpcProcedureSignature(name="TestProc", opnum=0, parameters=params)

    def test_input_count(self):
        params = [
            RpcParameter(name="a", ndr_type="int", direction="in"),
            RpcParameter(name="b", ndr_type="string", direction="in"),
            RpcParameter(name="c", ndr_type="int", direction="in"),
            RpcParameter(name="d", ndr_type="int", direction="out"),
            RpcParameter(name="e", ndr_type="int", direction="out"),
        ]
        sig = self._make_sig(params)
        assert sig.input_parameter_count == 3

    def test_has_string_inputs(self):
        params = [
            RpcParameter(name="name", ndr_type="string", direction="in"),
            RpcParameter(name="flags", ndr_type="int", direction="in"),
        ]
        sig = self._make_sig(params)
        assert sig.has_string_inputs is True

    def test_has_byte_buffer_inputs(self):
        params = [
            RpcParameter(name="buf", ndr_type="byte[]", direction="in", is_array=True),
        ]
        sig = self._make_sig(params)
        assert sig.has_byte_buffer_inputs is True

    def test_max_input_risk(self):
        params = [
            RpcParameter(name="flags", ndr_type="int", direction="in"),
            RpcParameter(name="name", ndr_type="string", direction="in"),
            RpcParameter(name="out_buf", ndr_type="byte[]", direction="out", is_array=True),
        ]
        sig = self._make_sig(params)
        assert sig.max_input_risk == pytest.approx(0.8, abs=0.05)


# ===================================================================
# Stub file parsing (synthetic content)
# ===================================================================


_MOCK_STUB_CS = textwrap.dedent("""\
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    // </auto-generated>
    //------------------------------------------------------------------------------

    // Source Executable: c:\\windows\\system32\\testsvc.dll
    // Interface ID: aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
    // Interface Version: 1.0

    namespace rpc_test
    {
        #region Marshal Helpers
        public struct Struct_0 { public int field0; }
        #endregion

        public sealed class Client : NtApiDotNet.Win32.Rpc.RpcClientBase
        {
            public Client() { }

            public uint DoFoo(string p0, int p1, out int p2)
            {
                // stub
            }

            public uint DoBar(byte[] p0, ref string p1, out Struct_0 p2)
            {
                // stub
            }

            public uint DoArrays(byte[] p0, int[] p1, string[] p2)
            {
                // stub
            }
        }
    }
""")


class TestStubFileParsing:
    """Parse synthetic .cs stub content via temp files."""

    @pytest.fixture()
    def stub_path(self, tmp_path: Path) -> Path:
        p = tmp_path / "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee_1.0.cs"
        p.write_text(_MOCK_STUB_CS, encoding="utf-8")
        return p

    def test_parse_header(self, stub_path: Path):
        stub = parse_stub_file(stub_path)
        assert stub is not None
        assert stub.interface_id == "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
        assert stub.interface_version == "1.0"
        assert "testsvc.dll" in stub.source_executable

    def test_parse_methods(self, stub_path: Path):
        stub = parse_stub_file(stub_path)
        assert stub is not None
        names = [p.name for p in stub.procedures]
        assert "DoFoo" in names
        assert "DoBar" in names

        do_foo = stub.get_procedure("DoFoo")
        assert do_foo is not None
        assert do_foo.return_type == "uint"
        type_names = [p.ndr_type for p in do_foo.parameters]
        assert "string" in type_names
        assert "int" in type_names

    def test_parse_out_params(self, stub_path: Path):
        stub = parse_stub_file(stub_path)
        assert stub is not None
        do_foo = stub.get_procedure("DoFoo")
        assert do_foo is not None
        out_params = [p for p in do_foo.parameters if p.direction == "out"]
        assert len(out_params) == 1
        assert out_params[0].name == "p2"

    def test_parse_ref_params(self, stub_path: Path):
        stub = parse_stub_file(stub_path)
        assert stub is not None
        do_bar = stub.get_procedure("DoBar")
        assert do_bar is not None
        inout_params = [p for p in do_bar.parameters if p.direction == "inout"]
        assert len(inout_params) == 1
        assert inout_params[0].name == "p1"

    def test_parse_array_types(self, stub_path: Path):
        stub = parse_stub_file(stub_path)
        assert stub is not None
        do_arrays = stub.get_procedure("DoArrays")
        assert do_arrays is not None
        for param in do_arrays.parameters:
            assert param.is_array is True, f"{param.name} ({param.ndr_type}) should be is_array=True"


# ===================================================================
# Live stub file tests (require actual stub assets)
# ===================================================================

_STUBS_PRESENT = _STUBS_DIR.exists()


@pytest.mark.skipif(not _STUBS_PRESENT, reason="stub files not present")
class TestStubFileLive:
    """Integration tests against real NtApiDotNet-generated stubs."""

    def test_parse_eventlog_stub(self):
        path = _STUBS_DIR / "f6beaff7-1e19-4fbb-9f8f-b89e2018337c_1.0.cs"
        stub = parse_stub_file(path)
        assert stub is not None
        assert stub.interface_id == "f6beaff7-1e19-4fbb-9f8f-b89e2018337c"
        assert "wevtsvc.dll" in stub.source_executable

        names = [p.name for p in stub.procedures]
        evt_procs = [n for n in names if n.startswith("EvtRpc_s_")]
        assert len(evt_procs) >= 5
        assert "EvtRpc_s_RegisterRemoteSubscription" in names
        assert "EvtRpc_s_ClearLog" in names

    def test_parse_rprn_stub(self):
        path = _STUBS_DIR / "12345678-1234-abcd-ef00-0123456789ab_1.0.cs"
        stub = parse_stub_file(path)
        assert stub is not None
        assert stub.interface_id == "12345678-1234-abcd-ef00-0123456789ab"
        assert "spoolsv" in stub.source_executable.lower()

        names = [p.name for p in stub.procedures]
        assert "RpcEnumPrinters" in names
        assert "RpcOpenPrinter" in names

    def test_parse_scmr_stub(self):
        path = _STUBS_DIR / "367abb81-9844-35f1-ad32-98f038001003_2.0.cs"
        stub = parse_stub_file(path)
        assert stub is not None
        assert stub.interface_id == "367abb81-9844-35f1-ad32-98f038001003"
        assert "services.exe" in stub.source_executable.lower()

        names = [p.name for p in stub.procedures]
        assert "RCloseServiceHandle" in names
        assert "ROpenSCManagerW" in names
        assert "RChangeServiceConfigW" in names

    def test_load_stubs_from_directory(self):
        stubs = load_stubs_from_directory(_STUBS_DIR)
        assert len(stubs) >= 400

        assert "f6beaff7-1e19-4fbb-9f8f-b89e2018337c" in stubs
        assert "12345678-1234-abcd-ef00-0123456789ab" in stubs
        assert "367abb81-9844-35f1-ad32-98f038001003" in stubs
